// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class BankAccount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject bankAccountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.BankAccount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IBAN("IBAN"),
		Bank("Bank"),
		Currency("Currency"),
		Input("Input"),
		BankAccount_User("Endorse.BankAccount_User");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BankAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BankAccount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject bankAccountMendixObject)
	{
		if (bankAccountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, bankAccountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.bankAccountMendixObject = bankAccountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.BankAccount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.BankAccount(context, mendixObject);
	}

	public static endorse.proxies.BankAccount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.BankAccount.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.BankAccount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.BankAccount.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of IBAN
	 */
	public final java.lang.String getIBAN()
	{
		return getIBAN(getContext());
	}

	/**
	 * @param context
	 * @return value of IBAN
	 */
	public final java.lang.String getIBAN(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.IBAN.toString());
	}

	/**
	 * Set value of IBAN
	 * @param iban
	 */
	public final void setIBAN(java.lang.String iban)
	{
		setIBAN(getContext(), iban);
	}

	/**
	 * Set value of IBAN
	 * @param context
	 * @param iban
	 */
	public final void setIBAN(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String iban)
	{
		getMendixObject().setValue(context, MemberNames.IBAN.toString(), iban);
	}

	/**
	 * Get value of Bank
	 * @param bank
	 */
	public final endorse.proxies.Bank_Account getBank()
	{
		return getBank(getContext());
	}

	/**
	 * @param context
	 * @return value of Bank
	 */
	public final endorse.proxies.Bank_Account getBank(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Bank.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Bank_Account.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Bank
	 * @param bank
	 */
	public final void setBank(endorse.proxies.Bank_Account bank)
	{
		setBank(getContext(), bank);
	}

	/**
	 * Set value of Bank
	 * @param context
	 * @param bank
	 */
	public final void setBank(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Bank_Account bank)
	{
		if (bank != null) {
			getMendixObject().setValue(context, MemberNames.Bank.toString(), bank.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Bank.toString(), null);
		}
	}

	/**
	 * Get value of Currency
	 * @param currency
	 */
	public final endorse.proxies.Bank_Currency getCurrency()
	{
		return getCurrency(getContext());
	}

	/**
	 * @param context
	 * @return value of Currency
	 */
	public final endorse.proxies.Bank_Currency getCurrency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Currency.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Bank_Currency.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Currency
	 * @param currency
	 */
	public final void setCurrency(endorse.proxies.Bank_Currency currency)
	{
		setCurrency(getContext(), currency);
	}

	/**
	 * Set value of Currency
	 * @param context
	 * @param currency
	 */
	public final void setCurrency(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Bank_Currency currency)
	{
		if (currency != null) {
			getMendixObject().setValue(context, MemberNames.Currency.toString(), currency.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Currency.toString(), null);
		}
	}

	/**
	 * @return value of Input
	 */
	public final java.math.BigDecimal getInput()
	{
		return getInput(getContext());
	}

	/**
	 * @param context
	 * @return value of Input
	 */
	public final java.math.BigDecimal getInput(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Input.toString());
	}

	/**
	 * Set value of Input
	 * @param input
	 */
	public final void setInput(java.math.BigDecimal input)
	{
		setInput(getContext(), input);
	}

	/**
	 * Set value of Input
	 * @param context
	 * @param input
	 */
	public final void setInput(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal input)
	{
		getMendixObject().setValue(context, MemberNames.Input.toString(), input);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BankAccount_User
	 */
	public final endorse.proxies.User getBankAccount_User() throws com.mendix.core.CoreException
	{
		return getBankAccount_User(getContext());
	}

	/**
	 * @param context
	 * @return value of BankAccount_User
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.User getBankAccount_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BankAccount_User.toString());
		if (identifier != null) {
			result = endorse.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BankAccount_User
	 * @param bankaccount_user
	 */
	public final void setBankAccount_User(endorse.proxies.User bankaccount_user)
	{
		setBankAccount_User(getContext(), bankaccount_user);
	}

	/**
	 * Set value of BankAccount_User
	 * @param context
	 * @param bankaccount_user
	 */
	public final void setBankAccount_User(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.User bankaccount_user)
	{
		if (bankaccount_user == null) {
			getMendixObject().setValue(context, MemberNames.BankAccount_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BankAccount_User.toString(), bankaccount_user.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return bankAccountMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.BankAccount that = (endorse.proxies.BankAccount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
