// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public enum Bank_Account
{
	YapiKredi(new java.lang.String[][] { new java.lang.String[] { "en_US", "YapiKredi" } }),
	Ziraat(new java.lang.String[][] { new java.lang.String[] { "en_US", "Ziraat" } }),
	Garanti(new java.lang.String[][] { new java.lang.String[] { "en_US", "Garanti" } }),
	Halkbank(new java.lang.String[][] { new java.lang.String[] { "en_US", "Halkbank" } }),
	Finansbank(new java.lang.String[][] { new java.lang.String[] { "en_US", "Finansbank" } }),
	Papara(new java.lang.String[][] { new java.lang.String[] { "en_US", "Papara" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Bank_Account(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "en_US");
	}

	public java.lang.String getCaption()
	{
		return captions.get("en_US");
	}
}
