// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class Branch implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject branchMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.Branch";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		BranchID("BranchID"),
		Name("Name"),
		Country("Country"),
		City("City"),
		Address("Address"),
		IsMain("IsMain"),
		CommissionRate("CommissionRate"),
		TotalCommissionIncome("TotalCommissionIncome"),
		DailyCommissionIncome("DailyCommissionIncome"),
		TransactionRequest_Completed("TransactionRequest_Completed"),
		Main_Branch("Endorse.Main_Branch");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Branch(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Branch(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject branchMendixObject)
	{
		if (branchMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, branchMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.branchMendixObject = branchMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.Branch initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.Branch(context, mendixObject);
	}

	public static endorse.proxies.Branch load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.Branch.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.Branch> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.Branch.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of BranchID
	 */
	public final java.lang.Long getBranchID()
	{
		return getBranchID(getContext());
	}

	/**
	 * @param context
	 * @return value of BranchID
	 */
	public final java.lang.Long getBranchID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.BranchID.toString());
	}

	/**
	 * Set value of BranchID
	 * @param branchid
	 */
	public final void setBranchID(java.lang.Long branchid)
	{
		setBranchID(getContext(), branchid);
	}

	/**
	 * Set value of BranchID
	 * @param context
	 * @param branchid
	 */
	public final void setBranchID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long branchid)
	{
		getMendixObject().setValue(context, MemberNames.BranchID.toString(), branchid);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Get value of Country
	 * @param country
	 */
	public final endorse.proxies.Location_Country getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final endorse.proxies.Location_Country getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Country.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Location_Country.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(endorse.proxies.Location_Country country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Location_Country country)
	{
		if (country != null) {
			getMendixObject().setValue(context, MemberNames.Country.toString(), country.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Country.toString(), null);
		}
	}

	/**
	 * Get value of City
	 * @param city
	 */
	public final endorse.proxies.Location_City getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final endorse.proxies.Location_City getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.City.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Location_City.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(endorse.proxies.Location_City city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Location_City city)
	{
		if (city != null) {
			getMendixObject().setValue(context, MemberNames.City.toString(), city.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.City.toString(), null);
		}
	}

	/**
	 * @return value of Address
	 */
	public final java.lang.String getAddress()
	{
		return getAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of Address
	 */
	public final java.lang.String getAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Address.toString());
	}

	/**
	 * Set value of Address
	 * @param address
	 */
	public final void setAddress(java.lang.String address)
	{
		setAddress(getContext(), address);
	}

	/**
	 * Set value of Address
	 * @param context
	 * @param address
	 */
	public final void setAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String address)
	{
		getMendixObject().setValue(context, MemberNames.Address.toString(), address);
	}

	/**
	 * @return value of IsMain
	 */
	public final java.lang.Boolean getIsMain()
	{
		return getIsMain(getContext());
	}

	/**
	 * @param context
	 * @return value of IsMain
	 */
	public final java.lang.Boolean getIsMain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsMain.toString());
	}

	/**
	 * Set value of IsMain
	 * @param ismain
	 */
	public final void setIsMain(java.lang.Boolean ismain)
	{
		setIsMain(getContext(), ismain);
	}

	/**
	 * Set value of IsMain
	 * @param context
	 * @param ismain
	 */
	public final void setIsMain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ismain)
	{
		getMendixObject().setValue(context, MemberNames.IsMain.toString(), ismain);
	}

	/**
	 * @return value of CommissionRate
	 */
	public final java.math.BigDecimal getCommissionRate()
	{
		return getCommissionRate(getContext());
	}

	/**
	 * @param context
	 * @return value of CommissionRate
	 */
	public final java.math.BigDecimal getCommissionRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CommissionRate.toString());
	}

	/**
	 * Set value of CommissionRate
	 * @param commissionrate
	 */
	public final void setCommissionRate(java.math.BigDecimal commissionrate)
	{
		setCommissionRate(getContext(), commissionrate);
	}

	/**
	 * Set value of CommissionRate
	 * @param context
	 * @param commissionrate
	 */
	public final void setCommissionRate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal commissionrate)
	{
		getMendixObject().setValue(context, MemberNames.CommissionRate.toString(), commissionrate);
	}

	/**
	 * @return value of TotalCommissionIncome
	 */
	public final java.math.BigDecimal getTotalCommissionIncome()
	{
		return getTotalCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCommissionIncome
	 */
	public final java.math.BigDecimal getTotalCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCommissionIncome.toString());
	}

	/**
	 * Set value of TotalCommissionIncome
	 * @param totalcommissionincome
	 */
	public final void setTotalCommissionIncome(java.math.BigDecimal totalcommissionincome)
	{
		setTotalCommissionIncome(getContext(), totalcommissionincome);
	}

	/**
	 * Set value of TotalCommissionIncome
	 * @param context
	 * @param totalcommissionincome
	 */
	public final void setTotalCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.TotalCommissionIncome.toString(), totalcommissionincome);
	}

	/**
	 * @return value of DailyCommissionIncome
	 */
	public final java.math.BigDecimal getDailyCommissionIncome()
	{
		return getDailyCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyCommissionIncome
	 */
	public final java.math.BigDecimal getDailyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DailyCommissionIncome.toString());
	}

	/**
	 * Set value of DailyCommissionIncome
	 * @param dailycommissionincome
	 */
	public final void setDailyCommissionIncome(java.math.BigDecimal dailycommissionincome)
	{
		setDailyCommissionIncome(getContext(), dailycommissionincome);
	}

	/**
	 * Set value of DailyCommissionIncome
	 * @param context
	 * @param dailycommissionincome
	 */
	public final void setDailyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dailycommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.DailyCommissionIncome.toString(), dailycommissionincome);
	}

	/**
	 * @return value of TransactionRequest_Completed
	 */
	public final java.lang.Integer getTransactionRequest_Completed()
	{
		return getTransactionRequest_Completed(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Completed
	 */
	public final java.lang.Integer getTransactionRequest_Completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TransactionRequest_Completed.toString());
	}

	/**
	 * Set value of TransactionRequest_Completed
	 * @param transactionrequest_completed
	 */
	public final void setTransactionRequest_Completed(java.lang.Integer transactionrequest_completed)
	{
		setTransactionRequest_Completed(getContext(), transactionrequest_completed);
	}

	/**
	 * Set value of TransactionRequest_Completed
	 * @param context
	 * @param transactionrequest_completed
	 */
	public final void setTransactionRequest_Completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transactionrequest_completed)
	{
		getMendixObject().setValue(context, MemberNames.TransactionRequest_Completed.toString(), transactionrequest_completed);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Main_Branch
	 */
	public final endorse.proxies.Branch getMain_Branch() throws com.mendix.core.CoreException
	{
		return getMain_Branch(getContext());
	}

	/**
	 * @param context
	 * @return value of Main_Branch
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Branch getMain_Branch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Branch result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Main_Branch.toString());
		if (identifier != null) {
			result = endorse.proxies.Branch.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Main_Branch
	 * @param main_branch
	 */
	public final void setMain_Branch(endorse.proxies.Branch main_branch)
	{
		setMain_Branch(getContext(), main_branch);
	}

	/**
	 * Set value of Main_Branch
	 * @param context
	 * @param main_branch
	 */
	public final void setMain_Branch(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Branch main_branch)
	{
		if (main_branch == null) {
			getMendixObject().setValue(context, MemberNames.Main_Branch.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Main_Branch.toString(), main_branch.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return branchMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.Branch that = (endorse.proxies.Branch) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
