// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class Coin implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject coinMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.Coin";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CoinID("CoinID"),
		Symbol("Symbol"),
		Name("Name"),
		MarketValue("MarketValue"),
		Change("Change"),
		Icon("Icon"),
		Coin_CustomCoinIcon("Endorse.Coin_CustomCoinIcon");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Coin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Coin(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject coinMendixObject)
	{
		if (coinMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, coinMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.coinMendixObject = coinMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.Coin initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.Coin(context, mendixObject);
	}

	public static endorse.proxies.Coin load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.Coin.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.Coin> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.Coin.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of CoinID
	 */
	public final java.lang.Long getCoinID()
	{
		return getCoinID(getContext());
	}

	/**
	 * @param context
	 * @return value of CoinID
	 */
	public final java.lang.Long getCoinID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.CoinID.toString());
	}

	/**
	 * Set value of CoinID
	 * @param coinid
	 */
	public final void setCoinID(java.lang.Long coinid)
	{
		setCoinID(getContext(), coinid);
	}

	/**
	 * Set value of CoinID
	 * @param context
	 * @param coinid
	 */
	public final void setCoinID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long coinid)
	{
		getMendixObject().setValue(context, MemberNames.CoinID.toString(), coinid);
	}

	/**
	 * @return value of Symbol
	 */
	public final java.lang.String getSymbol()
	{
		return getSymbol(getContext());
	}

	/**
	 * @param context
	 * @return value of Symbol
	 */
	public final java.lang.String getSymbol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Symbol.toString());
	}

	/**
	 * Set value of Symbol
	 * @param symbol
	 */
	public final void setSymbol(java.lang.String symbol)
	{
		setSymbol(getContext(), symbol);
	}

	/**
	 * Set value of Symbol
	 * @param context
	 * @param symbol
	 */
	public final void setSymbol(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String symbol)
	{
		getMendixObject().setValue(context, MemberNames.Symbol.toString(), symbol);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of MarketValue
	 */
	public final java.math.BigDecimal getMarketValue()
	{
		return getMarketValue(getContext());
	}

	/**
	 * @param context
	 * @return value of MarketValue
	 */
	public final java.math.BigDecimal getMarketValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MarketValue.toString());
	}

	/**
	 * Set value of MarketValue
	 * @param marketvalue
	 */
	public final void setMarketValue(java.math.BigDecimal marketvalue)
	{
		setMarketValue(getContext(), marketvalue);
	}

	/**
	 * Set value of MarketValue
	 * @param context
	 * @param marketvalue
	 */
	public final void setMarketValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal marketvalue)
	{
		getMendixObject().setValue(context, MemberNames.MarketValue.toString(), marketvalue);
	}

	/**
	 * @return value of Change
	 */
	public final java.math.BigDecimal getChange()
	{
		return getChange(getContext());
	}

	/**
	 * @param context
	 * @return value of Change
	 */
	public final java.math.BigDecimal getChange(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Change.toString());
	}

	/**
	 * Set value of Change
	 * @param change
	 */
	public final void setChange(java.math.BigDecimal change)
	{
		setChange(getContext(), change);
	}

	/**
	 * Set value of Change
	 * @param context
	 * @param change
	 */
	public final void setChange(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal change)
	{
		getMendixObject().setValue(context, MemberNames.Change.toString(), change);
	}

	/**
	 * @return value of Icon
	 */
	public final java.lang.String getIcon()
	{
		return getIcon(getContext());
	}

	/**
	 * @param context
	 * @return value of Icon
	 */
	public final java.lang.String getIcon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Icon.toString());
	}

	/**
	 * Set value of Icon
	 * @param icon
	 */
	public final void setIcon(java.lang.String icon)
	{
		setIcon(getContext(), icon);
	}

	/**
	 * Set value of Icon
	 * @param context
	 * @param icon
	 */
	public final void setIcon(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String icon)
	{
		getMendixObject().setValue(context, MemberNames.Icon.toString(), icon);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Coin_CustomCoinIcon
	 */
	public final endorse.proxies.CustomCoinIcon getCoin_CustomCoinIcon() throws com.mendix.core.CoreException
	{
		return getCoin_CustomCoinIcon(getContext());
	}

	/**
	 * @param context
	 * @return value of Coin_CustomCoinIcon
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.CustomCoinIcon getCoin_CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.CustomCoinIcon result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coin_CustomCoinIcon.toString());
		if (identifier != null) {
			result = endorse.proxies.CustomCoinIcon.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Coin_CustomCoinIcon
	 * @param coin_customcoinicon
	 */
	public final void setCoin_CustomCoinIcon(endorse.proxies.CustomCoinIcon coin_customcoinicon)
	{
		setCoin_CustomCoinIcon(getContext(), coin_customcoinicon);
	}

	/**
	 * Set value of Coin_CustomCoinIcon
	 * @param context
	 * @param coin_customcoinicon
	 */
	public final void setCoin_CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.CustomCoinIcon coin_customcoinicon)
	{
		if (coin_customcoinicon == null) {
			getMendixObject().setValue(context, MemberNames.Coin_CustomCoinIcon.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Coin_CustomCoinIcon.toString(), coin_customcoinicon.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return coinMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.Coin that = (endorse.proxies.Coin) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
