// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class CustomCoinIcon extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.CustomCoinIcon";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Coin_CustomCoinIcon("Endorse.Coin_CustomCoinIcon");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customCoinIconMendixObject)
	{
		super(context, customCoinIconMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, customCoinIconMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.CustomCoinIcon initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.CustomCoinIcon(context, mendixObject);
	}

	public static endorse.proxies.CustomCoinIcon load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.CustomCoinIcon.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.CustomCoinIcon> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.CustomCoinIcon.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Coin_CustomCoinIcon
	 */
	public final endorse.proxies.Coin getCoin_CustomCoinIcon() throws com.mendix.core.CoreException
	{
		return getCoin_CustomCoinIcon(getContext());
	}

	/**
	 * @param context
	 * @return value of Coin_CustomCoinIcon
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Coin getCoin_CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Coin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Coin_CustomCoinIcon.toString());
		if (identifier != null) {
			result = endorse.proxies.Coin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Coin_CustomCoinIcon
	 * @param coin_customcoinicon
	 */
	public final void setCoin_CustomCoinIcon(endorse.proxies.Coin coin_customcoinicon)
	{
		setCoin_CustomCoinIcon(getContext(), coin_customcoinicon);
	}

	/**
	 * Set value of Coin_CustomCoinIcon
	 * @param context
	 * @param coin_customcoinicon
	 */
	public final void setCoin_CustomCoinIcon(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Coin coin_customcoinicon)
	{
		if (coin_customcoinicon == null) {
			getMendixObject().setValue(context, MemberNames.Coin_CustomCoinIcon.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Coin_CustomCoinIcon.toString(), coin_customcoinicon.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.CustomCoinIcon that = (endorse.proxies.CustomCoinIcon) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
