// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class EmailFile extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.EmailFile";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		EmailFile_EmailRequest("Endorse.EmailFile_EmailRequest");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailFile(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailFile(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailFileMendixObject)
	{
		super(context, emailFileMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailFileMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.EmailFile initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.EmailFile(context, mendixObject);
	}

	public static endorse.proxies.EmailFile load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.EmailFile.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.EmailFile> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.EmailFile.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailFile_EmailRequest
	 */
	public final endorse.proxies.EmailRequest getEmailFile_EmailRequest() throws com.mendix.core.CoreException
	{
		return getEmailFile_EmailRequest(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailFile_EmailRequest
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.EmailRequest getEmailFile_EmailRequest(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.EmailRequest result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailFile_EmailRequest.toString());
		if (identifier != null) {
			result = endorse.proxies.EmailRequest.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailFile_EmailRequest
	 * @param emailfile_emailrequest
	 */
	public final void setEmailFile_EmailRequest(endorse.proxies.EmailRequest emailfile_emailrequest)
	{
		setEmailFile_EmailRequest(getContext(), emailfile_emailrequest);
	}

	/**
	 * Set value of EmailFile_EmailRequest
	 * @param context
	 * @param emailfile_emailrequest
	 */
	public final void setEmailFile_EmailRequest(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.EmailRequest emailfile_emailrequest)
	{
		if (emailfile_emailrequest == null) {
			getMendixObject().setValue(context, MemberNames.EmailFile_EmailRequest.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailFile_EmailRequest.toString(), emailfile_emailrequest.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.EmailFile that = (endorse.proxies.EmailFile) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
