// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class EstimatedValue implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject estimatedValueMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.EstimatedValue";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EstimatedValue("EstimatedValue");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EstimatedValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EstimatedValue(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject estimatedValueMendixObject)
	{
		if (estimatedValueMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, estimatedValueMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.estimatedValueMendixObject = estimatedValueMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.EstimatedValue initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.EstimatedValue(context, mendixObject);
	}

	public static endorse.proxies.EstimatedValue load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.EstimatedValue.initialize(context, mendixObject);
	}

	/**
	 * @return value of EstimatedValue
	 */
	public final java.math.BigDecimal getEstimatedValue()
	{
		return getEstimatedValue(getContext());
	}

	/**
	 * @param context
	 * @return value of EstimatedValue
	 */
	public final java.math.BigDecimal getEstimatedValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EstimatedValue.toString());
	}

	/**
	 * Set value of EstimatedValue
	 * @param estimatedvalue
	 */
	public final void setEstimatedValue(java.math.BigDecimal estimatedvalue)
	{
		setEstimatedValue(getContext(), estimatedvalue);
	}

	/**
	 * Set value of EstimatedValue
	 * @param context
	 * @param estimatedvalue
	 */
	public final void setEstimatedValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal estimatedvalue)
	{
		getMendixObject().setValue(context, MemberNames.EstimatedValue.toString(), estimatedvalue);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return estimatedValueMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.EstimatedValue that = (endorse.proxies.EstimatedValue) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
