// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class Report implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject reportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.Report";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DailyVolumeUSD("DailyVolumeUSD"),
		TotalCommissionIncome("TotalCommissionIncome"),
		DailyCommissionIncome("DailyCommissionIncome"),
		YearlyCommissionIncome("YearlyCommissionIncome"),
		WeeklyCommissionIncome("WeeklyCommissionIncome"),
		MonthlyCommissionIncome("MonthlyCommissionIncome"),
		TransactionRequest_Completed("TransactionRequest_Completed"),
		TransactionRequest_Pending("TransactionRequest_Pending"),
		TransactionRequest_Approved("TransactionRequest_Approved"),
		TransactionRequest_Rejected("TransactionRequest_Rejected");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Report(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Report(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject reportMendixObject)
	{
		if (reportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, reportMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.reportMendixObject = reportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.Report initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.Report(context, mendixObject);
	}

	public static endorse.proxies.Report load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.Report.initialize(context, mendixObject);
	}

	/**
	 * @return value of DailyVolumeUSD
	 */
	public final java.math.BigDecimal getDailyVolumeUSD()
	{
		return getDailyVolumeUSD(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyVolumeUSD
	 */
	public final java.math.BigDecimal getDailyVolumeUSD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DailyVolumeUSD.toString());
	}

	/**
	 * Set value of DailyVolumeUSD
	 * @param dailyvolumeusd
	 */
	public final void setDailyVolumeUSD(java.math.BigDecimal dailyvolumeusd)
	{
		setDailyVolumeUSD(getContext(), dailyvolumeusd);
	}

	/**
	 * Set value of DailyVolumeUSD
	 * @param context
	 * @param dailyvolumeusd
	 */
	public final void setDailyVolumeUSD(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dailyvolumeusd)
	{
		getMendixObject().setValue(context, MemberNames.DailyVolumeUSD.toString(), dailyvolumeusd);
	}

	/**
	 * @return value of TotalCommissionIncome
	 */
	public final java.math.BigDecimal getTotalCommissionIncome()
	{
		return getTotalCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCommissionIncome
	 */
	public final java.math.BigDecimal getTotalCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCommissionIncome.toString());
	}

	/**
	 * Set value of TotalCommissionIncome
	 * @param totalcommissionincome
	 */
	public final void setTotalCommissionIncome(java.math.BigDecimal totalcommissionincome)
	{
		setTotalCommissionIncome(getContext(), totalcommissionincome);
	}

	/**
	 * Set value of TotalCommissionIncome
	 * @param context
	 * @param totalcommissionincome
	 */
	public final void setTotalCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.TotalCommissionIncome.toString(), totalcommissionincome);
	}

	/**
	 * @return value of DailyCommissionIncome
	 */
	public final java.math.BigDecimal getDailyCommissionIncome()
	{
		return getDailyCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of DailyCommissionIncome
	 */
	public final java.math.BigDecimal getDailyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.DailyCommissionIncome.toString());
	}

	/**
	 * Set value of DailyCommissionIncome
	 * @param dailycommissionincome
	 */
	public final void setDailyCommissionIncome(java.math.BigDecimal dailycommissionincome)
	{
		setDailyCommissionIncome(getContext(), dailycommissionincome);
	}

	/**
	 * Set value of DailyCommissionIncome
	 * @param context
	 * @param dailycommissionincome
	 */
	public final void setDailyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal dailycommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.DailyCommissionIncome.toString(), dailycommissionincome);
	}

	/**
	 * @return value of YearlyCommissionIncome
	 */
	public final java.math.BigDecimal getYearlyCommissionIncome()
	{
		return getYearlyCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of YearlyCommissionIncome
	 */
	public final java.math.BigDecimal getYearlyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.YearlyCommissionIncome.toString());
	}

	/**
	 * Set value of YearlyCommissionIncome
	 * @param yearlycommissionincome
	 */
	public final void setYearlyCommissionIncome(java.math.BigDecimal yearlycommissionincome)
	{
		setYearlyCommissionIncome(getContext(), yearlycommissionincome);
	}

	/**
	 * Set value of YearlyCommissionIncome
	 * @param context
	 * @param yearlycommissionincome
	 */
	public final void setYearlyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal yearlycommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.YearlyCommissionIncome.toString(), yearlycommissionincome);
	}

	/**
	 * @return value of WeeklyCommissionIncome
	 */
	public final java.math.BigDecimal getWeeklyCommissionIncome()
	{
		return getWeeklyCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of WeeklyCommissionIncome
	 */
	public final java.math.BigDecimal getWeeklyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WeeklyCommissionIncome.toString());
	}

	/**
	 * Set value of WeeklyCommissionIncome
	 * @param weeklycommissionincome
	 */
	public final void setWeeklyCommissionIncome(java.math.BigDecimal weeklycommissionincome)
	{
		setWeeklyCommissionIncome(getContext(), weeklycommissionincome);
	}

	/**
	 * Set value of WeeklyCommissionIncome
	 * @param context
	 * @param weeklycommissionincome
	 */
	public final void setWeeklyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal weeklycommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.WeeklyCommissionIncome.toString(), weeklycommissionincome);
	}

	/**
	 * @return value of MonthlyCommissionIncome
	 */
	public final java.math.BigDecimal getMonthlyCommissionIncome()
	{
		return getMonthlyCommissionIncome(getContext());
	}

	/**
	 * @param context
	 * @return value of MonthlyCommissionIncome
	 */
	public final java.math.BigDecimal getMonthlyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MonthlyCommissionIncome.toString());
	}

	/**
	 * Set value of MonthlyCommissionIncome
	 * @param monthlycommissionincome
	 */
	public final void setMonthlyCommissionIncome(java.math.BigDecimal monthlycommissionincome)
	{
		setMonthlyCommissionIncome(getContext(), monthlycommissionincome);
	}

	/**
	 * Set value of MonthlyCommissionIncome
	 * @param context
	 * @param monthlycommissionincome
	 */
	public final void setMonthlyCommissionIncome(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal monthlycommissionincome)
	{
		getMendixObject().setValue(context, MemberNames.MonthlyCommissionIncome.toString(), monthlycommissionincome);
	}

	/**
	 * @return value of TransactionRequest_Completed
	 */
	public final java.lang.Integer getTransactionRequest_Completed()
	{
		return getTransactionRequest_Completed(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Completed
	 */
	public final java.lang.Integer getTransactionRequest_Completed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TransactionRequest_Completed.toString());
	}

	/**
	 * Set value of TransactionRequest_Completed
	 * @param transactionrequest_completed
	 */
	public final void setTransactionRequest_Completed(java.lang.Integer transactionrequest_completed)
	{
		setTransactionRequest_Completed(getContext(), transactionrequest_completed);
	}

	/**
	 * Set value of TransactionRequest_Completed
	 * @param context
	 * @param transactionrequest_completed
	 */
	public final void setTransactionRequest_Completed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transactionrequest_completed)
	{
		getMendixObject().setValue(context, MemberNames.TransactionRequest_Completed.toString(), transactionrequest_completed);
	}

	/**
	 * @return value of TransactionRequest_Pending
	 */
	public final java.lang.Integer getTransactionRequest_Pending()
	{
		return getTransactionRequest_Pending(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Pending
	 */
	public final java.lang.Integer getTransactionRequest_Pending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TransactionRequest_Pending.toString());
	}

	/**
	 * Set value of TransactionRequest_Pending
	 * @param transactionrequest_pending
	 */
	public final void setTransactionRequest_Pending(java.lang.Integer transactionrequest_pending)
	{
		setTransactionRequest_Pending(getContext(), transactionrequest_pending);
	}

	/**
	 * Set value of TransactionRequest_Pending
	 * @param context
	 * @param transactionrequest_pending
	 */
	public final void setTransactionRequest_Pending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transactionrequest_pending)
	{
		getMendixObject().setValue(context, MemberNames.TransactionRequest_Pending.toString(), transactionrequest_pending);
	}

	/**
	 * @return value of TransactionRequest_Approved
	 */
	public final java.lang.Integer getTransactionRequest_Approved()
	{
		return getTransactionRequest_Approved(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Approved
	 */
	public final java.lang.Integer getTransactionRequest_Approved(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TransactionRequest_Approved.toString());
	}

	/**
	 * Set value of TransactionRequest_Approved
	 * @param transactionrequest_approved
	 */
	public final void setTransactionRequest_Approved(java.lang.Integer transactionrequest_approved)
	{
		setTransactionRequest_Approved(getContext(), transactionrequest_approved);
	}

	/**
	 * Set value of TransactionRequest_Approved
	 * @param context
	 * @param transactionrequest_approved
	 */
	public final void setTransactionRequest_Approved(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transactionrequest_approved)
	{
		getMendixObject().setValue(context, MemberNames.TransactionRequest_Approved.toString(), transactionrequest_approved);
	}

	/**
	 * @return value of TransactionRequest_Rejected
	 */
	public final java.lang.Integer getTransactionRequest_Rejected()
	{
		return getTransactionRequest_Rejected(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Rejected
	 */
	public final java.lang.Integer getTransactionRequest_Rejected(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TransactionRequest_Rejected.toString());
	}

	/**
	 * Set value of TransactionRequest_Rejected
	 * @param transactionrequest_rejected
	 */
	public final void setTransactionRequest_Rejected(java.lang.Integer transactionrequest_rejected)
	{
		setTransactionRequest_Rejected(getContext(), transactionrequest_rejected);
	}

	/**
	 * Set value of TransactionRequest_Rejected
	 * @param context
	 * @param transactionrequest_rejected
	 */
	public final void setTransactionRequest_Rejected(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer transactionrequest_rejected)
	{
		getMendixObject().setValue(context, MemberNames.TransactionRequest_Rejected.toString(), transactionrequest_rejected);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return reportMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.Report that = (endorse.proxies.Report) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
