// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class TransactionRequest implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transactionRequestMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.TransactionRequest";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TXID("TXID"),
		TransactionType("TransactionType"),
		AmountCoin("AmountCoin"),
		AmountUSD("AmountUSD"),
		Price("Price"),
		TransactionStatus("TransactionStatus"),
		Commission("Commission"),
		TransactionRequest_Coin("Endorse.TransactionRequest_Coin"),
		TransactionRequest_Wallet("Endorse.TransactionRequest_Wallet"),
		TransactionRequest_User("Endorse.TransactionRequest_User"),
		TransactionRequest_Branch("Endorse.TransactionRequest_Branch");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransactionRequest(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TransactionRequest(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transactionRequestMendixObject)
	{
		if (transactionRequestMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, transactionRequestMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.transactionRequestMendixObject = transactionRequestMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.TransactionRequest initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.TransactionRequest(context, mendixObject);
	}

	public static endorse.proxies.TransactionRequest load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.TransactionRequest.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.TransactionRequest> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.TransactionRequest.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of TXID
	 */
	public final java.lang.Long getTXID()
	{
		return getTXID(getContext());
	}

	/**
	 * @param context
	 * @return value of TXID
	 */
	public final java.lang.Long getTXID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.TXID.toString());
	}

	/**
	 * Set value of TXID
	 * @param txid
	 */
	public final void setTXID(java.lang.Long txid)
	{
		setTXID(getContext(), txid);
	}

	/**
	 * Set value of TXID
	 * @param context
	 * @param txid
	 */
	public final void setTXID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long txid)
	{
		getMendixObject().setValue(context, MemberNames.TXID.toString(), txid);
	}

	/**
	 * Get value of TransactionType
	 * @param transactiontype
	 */
	public final endorse.proxies.Transaction_Type getTransactionType()
	{
		return getTransactionType(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionType
	 */
	public final endorse.proxies.Transaction_Type getTransactionType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TransactionType.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Transaction_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TransactionType
	 * @param transactiontype
	 */
	public final void setTransactionType(endorse.proxies.Transaction_Type transactiontype)
	{
		setTransactionType(getContext(), transactiontype);
	}

	/**
	 * Set value of TransactionType
	 * @param context
	 * @param transactiontype
	 */
	public final void setTransactionType(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Transaction_Type transactiontype)
	{
		if (transactiontype != null) {
			getMendixObject().setValue(context, MemberNames.TransactionType.toString(), transactiontype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionType.toString(), null);
		}
	}

	/**
	 * @return value of AmountCoin
	 */
	public final java.math.BigDecimal getAmountCoin()
	{
		return getAmountCoin(getContext());
	}

	/**
	 * @param context
	 * @return value of AmountCoin
	 */
	public final java.math.BigDecimal getAmountCoin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AmountCoin.toString());
	}

	/**
	 * Set value of AmountCoin
	 * @param amountcoin
	 */
	public final void setAmountCoin(java.math.BigDecimal amountcoin)
	{
		setAmountCoin(getContext(), amountcoin);
	}

	/**
	 * Set value of AmountCoin
	 * @param context
	 * @param amountcoin
	 */
	public final void setAmountCoin(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amountcoin)
	{
		getMendixObject().setValue(context, MemberNames.AmountCoin.toString(), amountcoin);
	}

	/**
	 * @return value of AmountUSD
	 */
	public final java.math.BigDecimal getAmountUSD()
	{
		return getAmountUSD(getContext());
	}

	/**
	 * @param context
	 * @return value of AmountUSD
	 */
	public final java.math.BigDecimal getAmountUSD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AmountUSD.toString());
	}

	/**
	 * Set value of AmountUSD
	 * @param amountusd
	 */
	public final void setAmountUSD(java.math.BigDecimal amountusd)
	{
		setAmountUSD(getContext(), amountusd);
	}

	/**
	 * Set value of AmountUSD
	 * @param context
	 * @param amountusd
	 */
	public final void setAmountUSD(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal amountusd)
	{
		getMendixObject().setValue(context, MemberNames.AmountUSD.toString(), amountusd);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * Get value of TransactionStatus
	 * @param transactionstatus
	 */
	public final endorse.proxies.Transaction_Status getTransactionStatus()
	{
		return getTransactionStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionStatus
	 */
	public final endorse.proxies.Transaction_Status getTransactionStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TransactionStatus.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Transaction_Status.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TransactionStatus
	 * @param transactionstatus
	 */
	public final void setTransactionStatus(endorse.proxies.Transaction_Status transactionstatus)
	{
		setTransactionStatus(getContext(), transactionstatus);
	}

	/**
	 * Set value of TransactionStatus
	 * @param context
	 * @param transactionstatus
	 */
	public final void setTransactionStatus(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Transaction_Status transactionstatus)
	{
		if (transactionstatus != null) {
			getMendixObject().setValue(context, MemberNames.TransactionStatus.toString(), transactionstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionStatus.toString(), null);
		}
	}

	/**
	 * @return value of Commission
	 */
	public final java.math.BigDecimal getCommission()
	{
		return getCommission(getContext());
	}

	/**
	 * @param context
	 * @return value of Commission
	 */
	public final java.math.BigDecimal getCommission(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Commission.toString());
	}

	/**
	 * Set value of Commission
	 * @param commission
	 */
	public final void setCommission(java.math.BigDecimal commission)
	{
		setCommission(getContext(), commission);
	}

	/**
	 * Set value of Commission
	 * @param context
	 * @param commission
	 */
	public final void setCommission(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal commission)
	{
		getMendixObject().setValue(context, MemberNames.Commission.toString(), commission);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionRequest_Coin
	 */
	public final endorse.proxies.Coin getTransactionRequest_Coin() throws com.mendix.core.CoreException
	{
		return getTransactionRequest_Coin(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Coin
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Coin getTransactionRequest_Coin(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Coin result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionRequest_Coin.toString());
		if (identifier != null) {
			result = endorse.proxies.Coin.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionRequest_Coin
	 * @param transactionrequest_coin
	 */
	public final void setTransactionRequest_Coin(endorse.proxies.Coin transactionrequest_coin)
	{
		setTransactionRequest_Coin(getContext(), transactionrequest_coin);
	}

	/**
	 * Set value of TransactionRequest_Coin
	 * @param context
	 * @param transactionrequest_coin
	 */
	public final void setTransactionRequest_Coin(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Coin transactionrequest_coin)
	{
		if (transactionrequest_coin == null) {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Coin.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Coin.toString(), transactionrequest_coin.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionRequest_Wallet
	 */
	public final endorse.proxies.Wallet getTransactionRequest_Wallet() throws com.mendix.core.CoreException
	{
		return getTransactionRequest_Wallet(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Wallet
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Wallet getTransactionRequest_Wallet(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Wallet result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionRequest_Wallet.toString());
		if (identifier != null) {
			result = endorse.proxies.Wallet.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionRequest_Wallet
	 * @param transactionrequest_wallet
	 */
	public final void setTransactionRequest_Wallet(endorse.proxies.Wallet transactionrequest_wallet)
	{
		setTransactionRequest_Wallet(getContext(), transactionrequest_wallet);
	}

	/**
	 * Set value of TransactionRequest_Wallet
	 * @param context
	 * @param transactionrequest_wallet
	 */
	public final void setTransactionRequest_Wallet(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Wallet transactionrequest_wallet)
	{
		if (transactionrequest_wallet == null) {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Wallet.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Wallet.toString(), transactionrequest_wallet.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionRequest_User
	 */
	public final endorse.proxies.User getTransactionRequest_User() throws com.mendix.core.CoreException
	{
		return getTransactionRequest_User(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_User
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.User getTransactionRequest_User(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionRequest_User.toString());
		if (identifier != null) {
			result = endorse.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionRequest_User
	 * @param transactionrequest_user
	 */
	public final void setTransactionRequest_User(endorse.proxies.User transactionrequest_user)
	{
		setTransactionRequest_User(getContext(), transactionrequest_user);
	}

	/**
	 * Set value of TransactionRequest_User
	 * @param context
	 * @param transactionrequest_user
	 */
	public final void setTransactionRequest_User(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.User transactionrequest_user)
	{
		if (transactionrequest_user == null) {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_User.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_User.toString(), transactionrequest_user.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TransactionRequest_Branch
	 */
	public final endorse.proxies.Branch getTransactionRequest_Branch() throws com.mendix.core.CoreException
	{
		return getTransactionRequest_Branch(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionRequest_Branch
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Branch getTransactionRequest_Branch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Branch result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TransactionRequest_Branch.toString());
		if (identifier != null) {
			result = endorse.proxies.Branch.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TransactionRequest_Branch
	 * @param transactionrequest_branch
	 */
	public final void setTransactionRequest_Branch(endorse.proxies.Branch transactionrequest_branch)
	{
		setTransactionRequest_Branch(getContext(), transactionrequest_branch);
	}

	/**
	 * Set value of TransactionRequest_Branch
	 * @param context
	 * @param transactionrequest_branch
	 */
	public final void setTransactionRequest_Branch(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Branch transactionrequest_branch)
	{
		if (transactionrequest_branch == null) {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Branch.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionRequest_Branch.toString(), transactionrequest_branch.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transactionRequestMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.TransactionRequest that = (endorse.proxies.TransactionRequest) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
