// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class User extends administration.proxies.Account
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.User";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PhoneNumber("PhoneNumber"),
		Balance("Balance"),
		TradeWithUSD("TradeWithUSD"),
		TotalCoinValue("TotalCoinValue"),
		Country("Country"),
		City("City"),
		Adress("Adress"),
		TransactionsViewMode("TransactionsViewMode"),
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		User_Employee("Endorse.User_Employee"),
		User_Customer("Endorse.User_Customer"),
		User_UserPhoto("Endorse.User_UserPhoto"),
		User_Branch("Endorse.User_Branch"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public User(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected User(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userMendixObject)
	{
		super(context, userMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, userMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.User initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("Endorse.Customer", mendixObject.getType())) {
			return endorse.proxies.Customer.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Endorse.Employee", mendixObject.getType())) {
			return endorse.proxies.Employee.initialize(context, mendixObject);
		}
		return new endorse.proxies.User(context, mendixObject);
	}

	public static endorse.proxies.User load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.User.initialize(context, mendixObject);
	}

	public static java.util.List<? extends endorse.proxies.User> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.User.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.Long getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.Long getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.Long phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of Balance
	 */
	public final java.math.BigDecimal getBalance()
	{
		return getBalance(getContext());
	}

	/**
	 * @param context
	 * @return value of Balance
	 */
	public final java.math.BigDecimal getBalance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Balance.toString());
	}

	/**
	 * Set value of Balance
	 * @param balance
	 */
	public final void setBalance(java.math.BigDecimal balance)
	{
		setBalance(getContext(), balance);
	}

	/**
	 * Set value of Balance
	 * @param context
	 * @param balance
	 */
	public final void setBalance(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal balance)
	{
		getMendixObject().setValue(context, MemberNames.Balance.toString(), balance);
	}

	/**
	 * @return value of TradeWithUSD
	 */
	public final java.lang.Boolean getTradeWithUSD()
	{
		return getTradeWithUSD(getContext());
	}

	/**
	 * @param context
	 * @return value of TradeWithUSD
	 */
	public final java.lang.Boolean getTradeWithUSD(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TradeWithUSD.toString());
	}

	/**
	 * Set value of TradeWithUSD
	 * @param tradewithusd
	 */
	public final void setTradeWithUSD(java.lang.Boolean tradewithusd)
	{
		setTradeWithUSD(getContext(), tradewithusd);
	}

	/**
	 * Set value of TradeWithUSD
	 * @param context
	 * @param tradewithusd
	 */
	public final void setTradeWithUSD(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tradewithusd)
	{
		getMendixObject().setValue(context, MemberNames.TradeWithUSD.toString(), tradewithusd);
	}

	/**
	 * @return value of TotalCoinValue
	 */
	public final java.math.BigDecimal getTotalCoinValue()
	{
		return getTotalCoinValue(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCoinValue
	 */
	public final java.math.BigDecimal getTotalCoinValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCoinValue.toString());
	}

	/**
	 * Set value of TotalCoinValue
	 * @param totalcoinvalue
	 */
	public final void setTotalCoinValue(java.math.BigDecimal totalcoinvalue)
	{
		setTotalCoinValue(getContext(), totalcoinvalue);
	}

	/**
	 * Set value of TotalCoinValue
	 * @param context
	 * @param totalcoinvalue
	 */
	public final void setTotalCoinValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcoinvalue)
	{
		getMendixObject().setValue(context, MemberNames.TotalCoinValue.toString(), totalcoinvalue);
	}

	/**
	 * Get value of Country
	 * @param country
	 */
	public final endorse.proxies.Location_Country getCountry()
	{
		return getCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Country
	 */
	public final endorse.proxies.Location_Country getCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Country.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Location_Country.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Country
	 * @param country
	 */
	public final void setCountry(endorse.proxies.Location_Country country)
	{
		setCountry(getContext(), country);
	}

	/**
	 * Set value of Country
	 * @param context
	 * @param country
	 */
	public final void setCountry(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Location_Country country)
	{
		if (country != null) {
			getMendixObject().setValue(context, MemberNames.Country.toString(), country.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Country.toString(), null);
		}
	}

	/**
	 * Get value of City
	 * @param city
	 */
	public final endorse.proxies.Location_City getCity()
	{
		return getCity(getContext());
	}

	/**
	 * @param context
	 * @return value of City
	 */
	public final endorse.proxies.Location_City getCity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.City.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.Location_City.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of City
	 * @param city
	 */
	public final void setCity(endorse.proxies.Location_City city)
	{
		setCity(getContext(), city);
	}

	/**
	 * Set value of City
	 * @param context
	 * @param city
	 */
	public final void setCity(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Location_City city)
	{
		if (city != null) {
			getMendixObject().setValue(context, MemberNames.City.toString(), city.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.City.toString(), null);
		}
	}

	/**
	 * @return value of Adress
	 */
	public final java.lang.String getAdress()
	{
		return getAdress(getContext());
	}

	/**
	 * @param context
	 * @return value of Adress
	 */
	public final java.lang.String getAdress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Adress.toString());
	}

	/**
	 * Set value of Adress
	 * @param adress
	 */
	public final void setAdress(java.lang.String adress)
	{
		setAdress(getContext(), adress);
	}

	/**
	 * Set value of Adress
	 * @param context
	 * @param adress
	 */
	public final void setAdress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String adress)
	{
		getMendixObject().setValue(context, MemberNames.Adress.toString(), adress);
	}

	/**
	 * Get value of TransactionsViewMode
	 * @param transactionsviewmode
	 */
	public final endorse.proxies.TransactionsViewMode getTransactionsViewMode()
	{
		return getTransactionsViewMode(getContext());
	}

	/**
	 * @param context
	 * @return value of TransactionsViewMode
	 */
	public final endorse.proxies.TransactionsViewMode getTransactionsViewMode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.TransactionsViewMode.toString());
		if (obj == null) {
			return null;
		}
		return endorse.proxies.TransactionsViewMode.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of TransactionsViewMode
	 * @param transactionsviewmode
	 */
	public final void setTransactionsViewMode(endorse.proxies.TransactionsViewMode transactionsviewmode)
	{
		setTransactionsViewMode(getContext(), transactionsviewmode);
	}

	/**
	 * Set value of TransactionsViewMode
	 * @param context
	 * @param transactionsviewmode
	 */
	public final void setTransactionsViewMode(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.TransactionsViewMode transactionsviewmode)
	{
		if (transactionsviewmode != null) {
			getMendixObject().setValue(context, MemberNames.TransactionsViewMode.toString(), transactionsviewmode.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.TransactionsViewMode.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_Employee
	 */
	public final endorse.proxies.Employee getUser_Employee() throws com.mendix.core.CoreException
	{
		return getUser_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Employee getUser_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Employee.toString());
		if (identifier != null) {
			result = endorse.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_Employee
	 * @param user_employee
	 */
	public final void setUser_Employee(endorse.proxies.Employee user_employee)
	{
		setUser_Employee(getContext(), user_employee);
	}

	/**
	 * Set value of User_Employee
	 * @param context
	 * @param user_employee
	 */
	public final void setUser_Employee(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Employee user_employee)
	{
		if (user_employee == null) {
			getMendixObject().setValue(context, MemberNames.User_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_Employee.toString(), user_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_Customer
	 */
	public final endorse.proxies.Customer getUser_Customer() throws com.mendix.core.CoreException
	{
		return getUser_Customer(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Customer
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Customer getUser_Customer(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Customer result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Customer.toString());
		if (identifier != null) {
			result = endorse.proxies.Customer.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_Customer
	 * @param user_customer
	 */
	public final void setUser_Customer(endorse.proxies.Customer user_customer)
	{
		setUser_Customer(getContext(), user_customer);
	}

	/**
	 * Set value of User_Customer
	 * @param context
	 * @param user_customer
	 */
	public final void setUser_Customer(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Customer user_customer)
	{
		if (user_customer == null) {
			getMendixObject().setValue(context, MemberNames.User_Customer.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_Customer.toString(), user_customer.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_UserPhoto
	 */
	public final endorse.proxies.UserPhoto getUser_UserPhoto() throws com.mendix.core.CoreException
	{
		return getUser_UserPhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of User_UserPhoto
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.UserPhoto getUser_UserPhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.UserPhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_UserPhoto.toString());
		if (identifier != null) {
			result = endorse.proxies.UserPhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_UserPhoto
	 * @param user_userphoto
	 */
	public final void setUser_UserPhoto(endorse.proxies.UserPhoto user_userphoto)
	{
		setUser_UserPhoto(getContext(), user_userphoto);
	}

	/**
	 * Set value of User_UserPhoto
	 * @param context
	 * @param user_userphoto
	 */
	public final void setUser_UserPhoto(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.UserPhoto user_userphoto)
	{
		if (user_userphoto == null) {
			getMendixObject().setValue(context, MemberNames.User_UserPhoto.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_UserPhoto.toString(), user_userphoto.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_Branch
	 */
	public final endorse.proxies.Branch getUser_Branch() throws com.mendix.core.CoreException
	{
		return getUser_Branch(getContext());
	}

	/**
	 * @param context
	 * @return value of User_Branch
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.Branch getUser_Branch(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.Branch result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_Branch.toString());
		if (identifier != null) {
			result = endorse.proxies.Branch.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_Branch
	 * @param user_branch
	 */
	public final void setUser_Branch(endorse.proxies.Branch user_branch)
	{
		setUser_Branch(getContext(), user_branch);
	}

	/**
	 * Set value of User_Branch
	 * @param context
	 * @param user_branch
	 */
	public final void setUser_Branch(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.Branch user_branch)
	{
		if (user_branch == null) {
			getMendixObject().setValue(context, MemberNames.User_Branch.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_Branch.toString(), user_branch.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.User that = (endorse.proxies.User) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
