// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies;

public class UserPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Endorse.UserPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		EnableCaching("EnableCaching"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		User_UserPhoto("Endorse.User_UserPhoto");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userPhotoMendixObject)
	{
		super(context, userPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, userPhotoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static endorse.proxies.UserPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new endorse.proxies.UserPhoto(context, mendixObject);
	}

	public static endorse.proxies.UserPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return endorse.proxies.UserPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<endorse.proxies.UserPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> endorse.proxies.UserPhoto.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of User_UserPhoto
	 */
	public final endorse.proxies.User getUser_UserPhoto() throws com.mendix.core.CoreException
	{
		return getUser_UserPhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of User_UserPhoto
	 * @throws com.mendix.core.CoreException
	 */
	public final endorse.proxies.User getUser_UserPhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		endorse.proxies.User result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.User_UserPhoto.toString());
		if (identifier != null) {
			result = endorse.proxies.User.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of User_UserPhoto
	 * @param user_userphoto
	 */
	public final void setUser_UserPhoto(endorse.proxies.User user_userphoto)
	{
		setUser_UserPhoto(getContext(), user_userphoto);
	}

	/**
	 * Set value of User_UserPhoto
	 * @param context
	 * @param user_userphoto
	 */
	public final void setUser_UserPhoto(com.mendix.systemwideinterfaces.core.IContext context, endorse.proxies.User user_userphoto)
	{
		if (user_userphoto == null) {
			getMendixObject().setValue(context, MemberNames.User_UserPhoto.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.User_UserPhoto.toString(), user_userphoto.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final endorse.proxies.UserPhoto that = (endorse.proxies.UserPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
