// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package mxmodelreflection.actions;

import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import mxmodelreflection.proxies.MxObjectType;
import java.util.stream.Collectors;

public class JA_ReferenceObjects extends CustomJavaAction<java.lang.String>
{
	/** @deprecated use objectReference.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __objectReference;
	private final mxmodelreflection.proxies.MxObjectReference objectReference;

	public JA_ReferenceObjects(
		IContext context,
		IMendixObject _objectReference
	)
	{
		super(context);
		this.__objectReference = _objectReference;
		this.objectReference = _objectReference == null ? null : mxmodelreflection.proxies.MxObjectReference.initialize(getContext(), _objectReference);
	}

	@java.lang.Override
	public java.lang.String executeAction() throws Exception
	{
		// BEGIN USER CODE
		if (objectReference == null) {
			return null;
		} else {
			return objectReference.getMxObjectReference_MxObjectType().stream().map(MxObjectType::getCompleteName).collect(Collectors.joining(","));
		}
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "JA_ReferenceObjects";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
