// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package endorse.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Endorse module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BankAccount_DepositBuilder(
		endorse.proxies.BankAccount _bankAccount
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_BankAccount_Deposit");
		builder = builder.withParam("BankAccount", _bankAccount);
		return builder;
	}

	public static void aCT_BankAccount_Deposit(
		IContext context,
		endorse.proxies.BankAccount _bankAccount
	)
	{
		aCT_BankAccount_DepositBuilder(
				_bankAccount
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BankAccount_SaveBuilder(
		endorse.proxies.BankAccount _bankAccount
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_BankAccount_Save");
		builder = builder.withParam("BankAccount", _bankAccount);
		return builder;
	}

	public static void aCT_BankAccount_Save(
		IContext context,
		endorse.proxies.BankAccount _bankAccount
	)
	{
		aCT_BankAccount_SaveBuilder(
				_bankAccount
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Branch_Commission_DecreaseBuilder(
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Branch_Commission_Decrease");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_Branch_Commission_Decrease(
		IContext context,
		endorse.proxies.User _user
	)
	{
		aCT_Branch_Commission_DecreaseBuilder(
				_user
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Branch_Commission_IncreaseBuilder(
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Branch_Commission_Increase");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_Branch_Commission_Increase(
		IContext context,
		endorse.proxies.User _user
	)
	{
		aCT_Branch_Commission_IncreaseBuilder(
				_user
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_CheckLimitBuilder(
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_CheckLimit");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		return builder;
	}

	public static boolean aCT_Coin_CheckLimit(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		Object result = aCT_Coin_CheckLimitBuilder(
				_user,
				_transactionRequest
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_Custom_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_Custom_Create");
		return builder;
	}

	public static void aCT_Coin_Custom_Create(IContext context)
	{
		aCT_Coin_Custom_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_Custom_SaveBuilder(
		endorse.proxies.Coin _cryptocurrency
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_Custom_Save");
		builder = builder.withParam("Cryptocurrency", _cryptocurrency);
		return builder;
	}

	public static void aCT_Coin_Custom_Save(
		IContext context,
		endorse.proxies.Coin _cryptocurrency
	)
	{
		aCT_Coin_Custom_SaveBuilder(
				_cryptocurrency
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_UploadPhotoBuilder(
		endorse.proxies.CustomCoinIcon _cryptocurrencyIcon,
		endorse.proxies.Coin _cryptocurrency
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_UploadPhoto");
		builder = builder.withParam("CryptocurrencyIcon", _cryptocurrencyIcon);
		builder = builder.withParam("Cryptocurrency", _cryptocurrency);
		return builder;
	}

	public static void aCT_Coin_UploadPhoto(
		IContext context,
		endorse.proxies.CustomCoinIcon _cryptocurrencyIcon,
		endorse.proxies.Coin _cryptocurrency
	)
	{
		aCT_Coin_UploadPhotoBuilder(
				_cryptocurrencyIcon,
				_cryptocurrency
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_WithCoin_BuyBuilder(
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_WithCoin_Buy");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static void aCT_Coin_WithCoin_Buy(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		aCT_Coin_WithCoin_BuyBuilder(
				_user,
				_transactionRequest,
				_coin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_WithUSD_BuyBuilder(
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_WithUSD_Buy");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static void aCT_Coin_WithUSD_Buy(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		aCT_Coin_WithUSD_BuyBuilder(
				_user,
				_transactionRequest,
				_coin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Coin_WithUSD_SellBuilder(
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Coin_WithUSD_Sell");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static void aCT_Coin_WithUSD_Sell(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.TransactionRequest _transactionRequest,
		endorse.proxies.Coin _coin
	)
	{
		aCT_Coin_WithUSD_SellBuilder(
				_user,
				_transactionRequest,
				_coin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TransactionRequest_ApproveBuilder(
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_TransactionRequest_Approve");
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		return builder;
	}

	public static void aCT_TransactionRequest_Approve(
		IContext context,
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		aCT_TransactionRequest_ApproveBuilder(
				_transactionRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TransactionRequest_Buy_PassBuilder(
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_TransactionRequest_Buy_Pass");
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static void aCT_TransactionRequest_Buy_Pass(
		IContext context,
		endorse.proxies.Coin _coin
	)
	{
		aCT_TransactionRequest_Buy_PassBuilder(
				_coin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TransactionRequest_Buy_RejectBuilder(
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_TransactionRequest_Buy_Reject");
		builder = builder.withParam("TransactionRequest", _transactionRequest);
		return builder;
	}

	public static void aCT_TransactionRequest_Buy_Reject(
		IContext context,
		endorse.proxies.TransactionRequest _transactionRequest
	)
	{
		aCT_TransactionRequest_Buy_RejectBuilder(
				_transactionRequest
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_TransactionRequest_Sell_PassBuilder(
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_TransactionRequest_Sell_Pass");
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static void aCT_TransactionRequest_Sell_Pass(
		IContext context,
		endorse.proxies.Coin _coin
	)
	{
		aCT_TransactionRequest_Sell_PassBuilder(
				_coin
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_AssignBuilder(
		endorse.proxies.User _user,
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_Assign");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static void aCT_User_Assign(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.Branch _branch
	)
	{
		aCT_User_AssignBuilder(
				_user,
				_branch
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_ChangePasswordBuilder(
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_ChangePassword");
		builder = builder.withParam("AccountPasswordData", _accountPasswordData);
		return builder;
	}

	public static void aCT_User_ChangePassword(
		IContext context,
		administration.proxies.AccountPasswordData _accountPasswordData
	)
	{
		aCT_User_ChangePasswordBuilder(
				_accountPasswordData
			)
			.execute(context);
	}
	/**
	 * Create a new user object and change the default attribute values so the user will be handled as a webservice user.
	 * Finally open the User_NewEdit form so all remaing user information can be set.
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_Create");
		return builder;
	}

	/**
	 * Create a new user object and change the default attribute values so the user will be handled as a webservice user.
	 * Finally open the User_NewEdit form so all remaing user information can be set.
	 */
	public static void aCT_User_Create(IContext context)
	{
		aCT_User_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_ShowPasswordFormBuilder(
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_ShowPasswordForm");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_User_ShowPasswordForm(
		IContext context,
		endorse.proxies.User _user
	)
	{
		aCT_User_ShowPasswordFormBuilder(
				_user
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_ToggleTradeWithUSDBuilder(
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_ToggleTradeWithUSD");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_User_ToggleTradeWithUSD(
		IContext context,
		endorse.proxies.User _user
	)
	{
		aCT_User_ToggleTradeWithUSDBuilder(
				_user
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_UnassignBuilder(
		endorse.proxies.User _user,
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_Unassign");
		builder = builder.withParam("User", _user);
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static void aCT_User_Unassign(
		IContext context,
		endorse.proxies.User _user,
		endorse.proxies.Branch _branch
	)
	{
		aCT_User_UnassignBuilder(
				_user,
				_branch
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_User_UploadPhotoBuilder(
		endorse.proxies.UserPhoto _userPhoto,
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_User_UploadPhoto");
		builder = builder.withParam("UserPhoto", _userPhoto);
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static void aCT_User_UploadPhoto(
		IContext context,
		endorse.proxies.UserPhoto _userPhoto,
		endorse.proxies.User _user
	)
	{
		aCT_User_UploadPhotoBuilder(
				_userPhoto,
				_user
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Wallet_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Wallet_Create");
		return builder;
	}

	public static void aCT_Wallet_Create(IContext context)
	{
		aCT_Wallet_CreateBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Wallet_CreateOrGetBuilder(
		endorse.proxies.Coin _coin
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Wallet_CreateOrGet");
		builder = builder.withParam("Coin", _coin);
		return builder;
	}

	public static endorse.proxies.Wallet aCT_Wallet_CreateOrGet(
		IContext context,
		endorse.proxies.Coin _coin
	)
	{
		Object result = aCT_Wallet_CreateOrGetBuilder(
				_coin
			)
			.execute(context);
		return result == null ? null : endorse.proxies.Wallet.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Wallet_SaveBuilder(
		endorse.proxies.Wallet _wallet
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.ACT_Wallet_Save");
		builder = builder.withParam("Wallet", _wallet);
		return builder;
	}

	public static void aCT_Wallet_Save(
		IContext context,
		endorse.proxies.Wallet _wallet
	)
	{
		aCT_Wallet_SaveBuilder(
				_wallet
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aPI_RestCall_CryptocurrencyBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.API_RestCall_Cryptocurrency");
		return builder;
	}

	public static java.util.List<endorse.proxies.Coin> aPI_RestCall_Cryptocurrency(IContext context)
	{
		Object result = aPI_RestCall_CryptocurrencyBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> endorse.proxies.Coin.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder blankBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.Blank");
		return builder;
	}

	public static void blank(IContext context)
	{
		blankBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cAL_CurrentUser_MicroflowBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.CAL_CurrentUser_Microflow");
		return builder;
	}

	public static endorse.proxies.User cAL_CurrentUser_Microflow(IContext context)
	{
		Object result = cAL_CurrentUser_MicroflowBuilder().execute(context);
		return result == null ? null : endorse.proxies.User.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cAL_User_DailyLimitBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.CAL_User_DailyLimit");
		return builder;
	}

	public static void cAL_User_DailyLimit(IContext context)
	{
		cAL_User_DailyLimitBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cAL_User_TotalCoinValueBuilder(
		endorse.proxies.User _user
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.CAL_User_TotalCoinValue");
		builder = builder.withParam("User", _user);
		return builder;
	}

	public static java.math.BigDecimal cAL_User_TotalCoinValue(
		IContext context,
		endorse.proxies.User _user
	)
	{
		Object result = cAL_User_TotalCoinValueBuilder(
				_user
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cAL_User_UsersFromNotThatBranchBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.CAL_User_UsersFromNotThatBranch");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.util.List<endorse.proxies.User> cAL_User_UsersFromNotThatBranch(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = cAL_User_UsersFromNotThatBranchBuilder(
				_branch
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> endorse.proxies.User.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_AllDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_AllData");
		return builder;
	}

	public static endorse.proxies.Report dS_Branch_AllData(IContext context)
	{
		Object result = dS_Branch_AllDataBuilder().execute(context);
		return result == null ? null : endorse.proxies.Report.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_CommissionIncome_DailyBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_CommissionIncome_Daily");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.math.BigDecimal dS_Branch_CommissionIncome_Daily(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_CommissionIncome_DailyBuilder(
				_branch
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_CommissionIncome_MonthlyBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_CommissionIncome_Monthly");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.math.BigDecimal dS_Branch_CommissionIncome_Monthly(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_CommissionIncome_MonthlyBuilder(
				_branch
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_CommissionIncome_TotalBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_CommissionIncome_Total");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.math.BigDecimal dS_Branch_CommissionIncome_Total(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_CommissionIncome_TotalBuilder(
				_branch
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_CommissionIncome_WeeklyBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_CommissionIncome_Weekly");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.math.BigDecimal dS_Branch_CommissionIncome_Weekly(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_CommissionIncome_WeeklyBuilder(
				_branch
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_CommissionIncome_YearlyBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_CommissionIncome_Yearly");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.math.BigDecimal dS_Branch_CommissionIncome_Yearly(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_CommissionIncome_YearlyBuilder(
				_branch
			)
			.execute(context);
		return (java.math.BigDecimal) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_ApprovedBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Approved");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.lang.Long dS_Branch_TransactionRequest_Approved(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_TransactionRequest_ApprovedBuilder(
				_branch
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_CompletedBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Completed");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.lang.Long dS_Branch_TransactionRequest_Completed(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_TransactionRequest_CompletedBuilder(
				_branch
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_GetBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Get");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.util.List<endorse.proxies.TransactionRequest> dS_Branch_TransactionRequest_Get(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_TransactionRequest_GetBuilder(
				_branch
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> endorse.proxies.TransactionRequest.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_PendingBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Pending");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.lang.Long dS_Branch_TransactionRequest_Pending(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_TransactionRequest_PendingBuilder(
				_branch
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_RejectedBuilder(
		endorse.proxies.Branch _branch
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Rejected");
		builder = builder.withParam("Branch", _branch);
		return builder;
	}

	public static java.lang.Long dS_Branch_TransactionRequest_Rejected(
		IContext context,
		endorse.proxies.Branch _branch
	)
	{
		Object result = dS_Branch_TransactionRequest_RejectedBuilder(
				_branch
			)
			.execute(context);
		return (java.lang.Long) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Branch_TransactionRequest_WidgetBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_Branch_TransactionRequest_Widget");
		return builder;
	}

	public static endorse.proxies.Report dS_Branch_TransactionRequest_Widget(IContext context)
	{
		Object result = dS_Branch_TransactionRequest_WidgetBuilder().execute(context);
		return result == null ? null : endorse.proxies.Report.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_GetEstimatedValueHelperBuilder(
		endorse.proxies.Wallet _wallet
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Endorse.DS_GetEstimatedValueHelper");
		builder = builder.withParam("Wallet", _wallet);
		return builder;
	}

	public static endorse.proxies.EstimatedValue dS_GetEstimatedValueHelper(
		IContext context,
		endorse.proxies.Wallet _wallet
	)
	{
		Object result = dS_GetEstimatedValueHelperBuilder(
				_wallet
			)
			.execute(context);
		return result == null ? null : endorse.proxies.EstimatedValue.initialize(context, (IMendixObject) result);
	}
}
