// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class Attachment extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.Attachment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ContentID("ContentID"),
		attachmentName("attachmentName"),
		attachmentSize("attachmentSize"),
		attachmentContentType("attachmentContentType"),
		Position("Position"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Attachment_EmailMessage("Email_Connector.Attachment_EmailMessage"),
		Attachment_EmailTemplate("Email_Connector.Attachment_EmailTemplate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Attachment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Attachment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject attachmentMendixObject)
	{
		super(context, attachmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, attachmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.Attachment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.Attachment(context, mendixObject);
	}

	public static email_connector.proxies.Attachment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.Attachment.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.Attachment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.Attachment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ContentID
	 */
	public final java.lang.String getContentID()
	{
		return getContentID(getContext());
	}

	/**
	 * @param context
	 * @return value of ContentID
	 */
	public final java.lang.String getContentID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ContentID.toString());
	}

	/**
	 * Set value of ContentID
	 * @param contentid
	 */
	public final void setContentID(java.lang.String contentid)
	{
		setContentID(getContext(), contentid);
	}

	/**
	 * Set value of ContentID
	 * @param context
	 * @param contentid
	 */
	public final void setContentID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String contentid)
	{
		getMendixObject().setValue(context, MemberNames.ContentID.toString(), contentid);
	}

	/**
	 * @return value of attachmentName
	 */
	public final java.lang.String getattachmentName()
	{
		return getattachmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of attachmentName
	 */
	public final java.lang.String getattachmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.attachmentName.toString());
	}

	/**
	 * Set value of attachmentName
	 * @param attachmentname
	 */
	public final void setattachmentName(java.lang.String attachmentname)
	{
		setattachmentName(getContext(), attachmentname);
	}

	/**
	 * Set value of attachmentName
	 * @param context
	 * @param attachmentname
	 */
	public final void setattachmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attachmentname)
	{
		getMendixObject().setValue(context, MemberNames.attachmentName.toString(), attachmentname);
	}

	/**
	 * @return value of attachmentSize
	 */
	public final java.lang.Integer getattachmentSize()
	{
		return getattachmentSize(getContext());
	}

	/**
	 * @param context
	 * @return value of attachmentSize
	 */
	public final java.lang.Integer getattachmentSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.attachmentSize.toString());
	}

	/**
	 * Set value of attachmentSize
	 * @param attachmentsize
	 */
	public final void setattachmentSize(java.lang.Integer attachmentsize)
	{
		setattachmentSize(getContext(), attachmentsize);
	}

	/**
	 * Set value of attachmentSize
	 * @param context
	 * @param attachmentsize
	 */
	public final void setattachmentSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer attachmentsize)
	{
		getMendixObject().setValue(context, MemberNames.attachmentSize.toString(), attachmentsize);
	}

	/**
	 * @return value of attachmentContentType
	 */
	public final java.lang.String getattachmentContentType()
	{
		return getattachmentContentType(getContext());
	}

	/**
	 * @param context
	 * @return value of attachmentContentType
	 */
	public final java.lang.String getattachmentContentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.attachmentContentType.toString());
	}

	/**
	 * Set value of attachmentContentType
	 * @param attachmentcontenttype
	 */
	public final void setattachmentContentType(java.lang.String attachmentcontenttype)
	{
		setattachmentContentType(getContext(), attachmentcontenttype);
	}

	/**
	 * Set value of attachmentContentType
	 * @param context
	 * @param attachmentcontenttype
	 */
	public final void setattachmentContentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String attachmentcontenttype)
	{
		getMendixObject().setValue(context, MemberNames.attachmentContentType.toString(), attachmentcontenttype);
	}

	/**
	 * Get value of Position
	 * @param position
	 */
	public final email_connector.proxies.ENUM_AttachmentPosition getPosition()
	{
		return getPosition(getContext());
	}

	/**
	 * @param context
	 * @return value of Position
	 */
	public final email_connector.proxies.ENUM_AttachmentPosition getPosition(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Position.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_AttachmentPosition.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Position
	 * @param position
	 */
	public final void setPosition(email_connector.proxies.ENUM_AttachmentPosition position)
	{
		setPosition(getContext(), position);
	}

	/**
	 * Set value of Position
	 * @param context
	 * @param position
	 */
	public final void setPosition(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_AttachmentPosition position)
	{
		if (position != null) {
			getMendixObject().setValue(context, MemberNames.Position.toString(), position.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Position.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Attachment_EmailMessage
	 */
	public final email_connector.proxies.EmailMessage getAttachment_EmailMessage() throws com.mendix.core.CoreException
	{
		return getAttachment_EmailMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachment_EmailMessage
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailMessage getAttachment_EmailMessage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailMessage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachment_EmailMessage.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailMessage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Attachment_EmailMessage
	 * @param attachment_emailmessage
	 */
	public final void setAttachment_EmailMessage(email_connector.proxies.EmailMessage attachment_emailmessage)
	{
		setAttachment_EmailMessage(getContext(), attachment_emailmessage);
	}

	/**
	 * Set value of Attachment_EmailMessage
	 * @param context
	 * @param attachment_emailmessage
	 */
	public final void setAttachment_EmailMessage(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailMessage attachment_emailmessage)
	{
		if (attachment_emailmessage == null) {
			getMendixObject().setValue(context, MemberNames.Attachment_EmailMessage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Attachment_EmailMessage.toString(), attachment_emailmessage.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Attachment_EmailTemplate
	 */
	public final email_connector.proxies.EmailTemplate getAttachment_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getAttachment_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of Attachment_EmailTemplate
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailTemplate getAttachment_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Attachment_EmailTemplate.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailTemplate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Attachment_EmailTemplate
	 * @param attachment_emailtemplate
	 */
	public final void setAttachment_EmailTemplate(email_connector.proxies.EmailTemplate attachment_emailtemplate)
	{
		setAttachment_EmailTemplate(getContext(), attachment_emailtemplate);
	}

	/**
	 * Set value of Attachment_EmailTemplate
	 * @param context
	 * @param attachment_emailtemplate
	 */
	public final void setAttachment_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailTemplate attachment_emailtemplate)
	{
		if (attachment_emailtemplate == null) {
			getMendixObject().setValue(context, MemberNames.Attachment_EmailTemplate.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Attachment_EmailTemplate.toString(), attachment_emailtemplate.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.Attachment that = (email_connector.proxies.Attachment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
