// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class EmailAccount_NPE implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailAccount_NPEMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.EmailAccount_NPE";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Password("Password"),
		EmailAccount_NPE_EmailAccount("Email_Connector.EmailAccount_NPE_EmailAccount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailAccount_NPE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailAccount_NPE(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailAccount_NPEMendixObject)
	{
		if (emailAccount_NPEMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailAccount_NPEMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailAccount_NPEMendixObject = emailAccount_NPEMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.EmailAccount_NPE initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.EmailAccount_NPE(context, mendixObject);
	}

	public static email_connector.proxies.EmailAccount_NPE load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.EmailAccount_NPE.initialize(context, mendixObject);
	}

	/**
	 * @return value of Password
	 */
	public final java.lang.String getPassword()
	{
		return getPassword(getContext());
	}

	/**
	 * @param context
	 * @return value of Password
	 */
	public final java.lang.String getPassword(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Password.toString());
	}

	/**
	 * Set value of Password
	 * @param password
	 */
	public final void setPassword(java.lang.String password)
	{
		setPassword(getContext(), password);
	}

	/**
	 * Set value of Password
	 * @param context
	 * @param password
	 */
	public final void setPassword(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String password)
	{
		getMendixObject().setValue(context, MemberNames.Password.toString(), password);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailAccount_NPE_EmailAccount
	 */
	public final email_connector.proxies.EmailAccount getEmailAccount_NPE_EmailAccount() throws com.mendix.core.CoreException
	{
		return getEmailAccount_NPE_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailAccount_NPE_EmailAccount
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailAccount getEmailAccount_NPE_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailAccount_NPE_EmailAccount.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailAccount.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailAccount_NPE_EmailAccount
	 * @param emailaccount_npe_emailaccount
	 */
	public final void setEmailAccount_NPE_EmailAccount(email_connector.proxies.EmailAccount emailaccount_npe_emailaccount)
	{
		setEmailAccount_NPE_EmailAccount(getContext(), emailaccount_npe_emailaccount);
	}

	/**
	 * Set value of EmailAccount_NPE_EmailAccount
	 * @param context
	 * @param emailaccount_npe_emailaccount
	 */
	public final void setEmailAccount_NPE_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailAccount emailaccount_npe_emailaccount)
	{
		if (emailaccount_npe_emailaccount == null) {
			getMendixObject().setValue(context, MemberNames.EmailAccount_NPE_EmailAccount.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailAccount_NPE_EmailAccount.toString(), emailaccount_npe_emailaccount.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailAccount_NPEMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.EmailAccount_NPE that = (email_connector.proxies.EmailAccount_NPE) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
