// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class EmailMessage implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject emailMessageMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.EmailMessage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Subject("Subject"),
		SentDate("SentDate"),
		RetrieveDate("RetrieveDate"),
		From("From"),
		To("To"),
		CC("CC"),
		BCC("BCC"),
		Content("Content"),
		UseOnlyPlainText("UseOnlyPlainText"),
		hasAttachments("hasAttachments"),
		Size("Size"),
		FromDisplayName("FromDisplayName"),
		ReplyTo("ReplyTo"),
		PlainBody("PlainBody"),
		QueuedForSending("QueuedForSending"),
		ResendAttempts("ResendAttempts"),
		LastSendError("LastSendError"),
		LastSendAttemptAt("LastSendAttemptAt"),
		Status("Status"),
		isSigned("isSigned"),
		isEncrypted("isEncrypted"),
		RecipientsToggle("RecipientsToggle"),
		EmailMessage_EmailTemplate("Email_Connector.EmailMessage_EmailTemplate"),
		EmailMessage_EmailAccount("Email_Connector.EmailMessage_EmailAccount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EmailMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EmailMessage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject emailMessageMendixObject)
	{
		if (emailMessageMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, emailMessageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.emailMessageMendixObject = emailMessageMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.EmailMessage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.EmailMessage(context, mendixObject);
	}

	public static email_connector.proxies.EmailMessage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.EmailMessage.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.EmailMessage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.EmailMessage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Subject
	 */
	public final java.lang.String getSubject()
	{
		return getSubject(getContext());
	}

	/**
	 * @param context
	 * @return value of Subject
	 */
	public final java.lang.String getSubject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Subject.toString());
	}

	/**
	 * Set value of Subject
	 * @param subject
	 */
	public final void setSubject(java.lang.String subject)
	{
		setSubject(getContext(), subject);
	}

	/**
	 * Set value of Subject
	 * @param context
	 * @param subject
	 */
	public final void setSubject(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String subject)
	{
		getMendixObject().setValue(context, MemberNames.Subject.toString(), subject);
	}

	/**
	 * @return value of SentDate
	 */
	public final java.util.Date getSentDate()
	{
		return getSentDate(getContext());
	}

	/**
	 * @param context
	 * @return value of SentDate
	 */
	public final java.util.Date getSentDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.SentDate.toString());
	}

	/**
	 * Set value of SentDate
	 * @param sentdate
	 */
	public final void setSentDate(java.util.Date sentdate)
	{
		setSentDate(getContext(), sentdate);
	}

	/**
	 * Set value of SentDate
	 * @param context
	 * @param sentdate
	 */
	public final void setSentDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date sentdate)
	{
		getMendixObject().setValue(context, MemberNames.SentDate.toString(), sentdate);
	}

	/**
	 * @return value of RetrieveDate
	 */
	public final java.util.Date getRetrieveDate()
	{
		return getRetrieveDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RetrieveDate
	 */
	public final java.util.Date getRetrieveDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RetrieveDate.toString());
	}

	/**
	 * Set value of RetrieveDate
	 * @param retrievedate
	 */
	public final void setRetrieveDate(java.util.Date retrievedate)
	{
		setRetrieveDate(getContext(), retrievedate);
	}

	/**
	 * Set value of RetrieveDate
	 * @param context
	 * @param retrievedate
	 */
	public final void setRetrieveDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date retrievedate)
	{
		getMendixObject().setValue(context, MemberNames.RetrieveDate.toString(), retrievedate);
	}

	/**
	 * @return value of From
	 */
	public final java.lang.String getFrom()
	{
		return getFrom(getContext());
	}

	/**
	 * @param context
	 * @return value of From
	 */
	public final java.lang.String getFrom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.From.toString());
	}

	/**
	 * Set value of From
	 * @param from
	 */
	public final void setFrom(java.lang.String from)
	{
		setFrom(getContext(), from);
	}

	/**
	 * Set value of From
	 * @param context
	 * @param from
	 */
	public final void setFrom(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String from)
	{
		getMendixObject().setValue(context, MemberNames.From.toString(), from);
	}

	/**
	 * @return value of To
	 */
	public final java.lang.String getTo()
	{
		return getTo(getContext());
	}

	/**
	 * @param context
	 * @return value of To
	 */
	public final java.lang.String getTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.To.toString());
	}

	/**
	 * Set value of To
	 * @param to
	 */
	public final void setTo(java.lang.String to)
	{
		setTo(getContext(), to);
	}

	/**
	 * Set value of To
	 * @param context
	 * @param to
	 */
	public final void setTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String to)
	{
		getMendixObject().setValue(context, MemberNames.To.toString(), to);
	}

	/**
	 * @return value of CC
	 */
	public final java.lang.String getCC()
	{
		return getCC(getContext());
	}

	/**
	 * @param context
	 * @return value of CC
	 */
	public final java.lang.String getCC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CC.toString());
	}

	/**
	 * Set value of CC
	 * @param cc
	 */
	public final void setCC(java.lang.String cc)
	{
		setCC(getContext(), cc);
	}

	/**
	 * Set value of CC
	 * @param context
	 * @param cc
	 */
	public final void setCC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cc)
	{
		getMendixObject().setValue(context, MemberNames.CC.toString(), cc);
	}

	/**
	 * @return value of BCC
	 */
	public final java.lang.String getBCC()
	{
		return getBCC(getContext());
	}

	/**
	 * @param context
	 * @return value of BCC
	 */
	public final java.lang.String getBCC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.BCC.toString());
	}

	/**
	 * Set value of BCC
	 * @param bcc
	 */
	public final void setBCC(java.lang.String bcc)
	{
		setBCC(getContext(), bcc);
	}

	/**
	 * Set value of BCC
	 * @param context
	 * @param bcc
	 */
	public final void setBCC(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String bcc)
	{
		getMendixObject().setValue(context, MemberNames.BCC.toString(), bcc);
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of UseOnlyPlainText
	 */
	public final java.lang.Boolean getUseOnlyPlainText()
	{
		return getUseOnlyPlainText(getContext());
	}

	/**
	 * @param context
	 * @return value of UseOnlyPlainText
	 */
	public final java.lang.Boolean getUseOnlyPlainText(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseOnlyPlainText.toString());
	}

	/**
	 * Set value of UseOnlyPlainText
	 * @param useonlyplaintext
	 */
	public final void setUseOnlyPlainText(java.lang.Boolean useonlyplaintext)
	{
		setUseOnlyPlainText(getContext(), useonlyplaintext);
	}

	/**
	 * Set value of UseOnlyPlainText
	 * @param context
	 * @param useonlyplaintext
	 */
	public final void setUseOnlyPlainText(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean useonlyplaintext)
	{
		getMendixObject().setValue(context, MemberNames.UseOnlyPlainText.toString(), useonlyplaintext);
	}

	/**
	 * @return value of hasAttachments
	 */
	public final java.lang.Boolean gethasAttachments()
	{
		return gethasAttachments(getContext());
	}

	/**
	 * @param context
	 * @return value of hasAttachments
	 */
	public final java.lang.Boolean gethasAttachments(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.hasAttachments.toString());
	}

	/**
	 * Set value of hasAttachments
	 * @param hasattachments
	 */
	public final void sethasAttachments(java.lang.Boolean hasattachments)
	{
		sethasAttachments(getContext(), hasattachments);
	}

	/**
	 * Set value of hasAttachments
	 * @param context
	 * @param hasattachments
	 */
	public final void sethasAttachments(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasattachments)
	{
		getMendixObject().setValue(context, MemberNames.hasAttachments.toString(), hasattachments);
	}

	/**
	 * @return value of Size
	 */
	public final java.lang.Integer getSize()
	{
		return getSize(getContext());
	}

	/**
	 * @param context
	 * @return value of Size
	 */
	public final java.lang.Integer getSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Size.toString());
	}

	/**
	 * Set value of Size
	 * @param size
	 */
	public final void setSize(java.lang.Integer size)
	{
		setSize(getContext(), size);
	}

	/**
	 * Set value of Size
	 * @param context
	 * @param size
	 */
	public final void setSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer size)
	{
		getMendixObject().setValue(context, MemberNames.Size.toString(), size);
	}

	/**
	 * @return value of FromDisplayName
	 */
	public final java.lang.String getFromDisplayName()
	{
		return getFromDisplayName(getContext());
	}

	/**
	 * @param context
	 * @return value of FromDisplayName
	 */
	public final java.lang.String getFromDisplayName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FromDisplayName.toString());
	}

	/**
	 * Set value of FromDisplayName
	 * @param fromdisplayname
	 */
	public final void setFromDisplayName(java.lang.String fromdisplayname)
	{
		setFromDisplayName(getContext(), fromdisplayname);
	}

	/**
	 * Set value of FromDisplayName
	 * @param context
	 * @param fromdisplayname
	 */
	public final void setFromDisplayName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fromdisplayname)
	{
		getMendixObject().setValue(context, MemberNames.FromDisplayName.toString(), fromdisplayname);
	}

	/**
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo()
	{
		return getReplyTo(getContext());
	}

	/**
	 * @param context
	 * @return value of ReplyTo
	 */
	public final java.lang.String getReplyTo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReplyTo.toString());
	}

	/**
	 * Set value of ReplyTo
	 * @param replyto
	 */
	public final void setReplyTo(java.lang.String replyto)
	{
		setReplyTo(getContext(), replyto);
	}

	/**
	 * Set value of ReplyTo
	 * @param context
	 * @param replyto
	 */
	public final void setReplyTo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String replyto)
	{
		getMendixObject().setValue(context, MemberNames.ReplyTo.toString(), replyto);
	}

	/**
	 * @return value of PlainBody
	 */
	public final java.lang.String getPlainBody()
	{
		return getPlainBody(getContext());
	}

	/**
	 * @param context
	 * @return value of PlainBody
	 */
	public final java.lang.String getPlainBody(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlainBody.toString());
	}

	/**
	 * Set value of PlainBody
	 * @param plainbody
	 */
	public final void setPlainBody(java.lang.String plainbody)
	{
		setPlainBody(getContext(), plainbody);
	}

	/**
	 * Set value of PlainBody
	 * @param context
	 * @param plainbody
	 */
	public final void setPlainBody(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plainbody)
	{
		getMendixObject().setValue(context, MemberNames.PlainBody.toString(), plainbody);
	}

	/**
	 * @return value of QueuedForSending
	 */
	public final java.lang.Boolean getQueuedForSending()
	{
		return getQueuedForSending(getContext());
	}

	/**
	 * @param context
	 * @return value of QueuedForSending
	 */
	public final java.lang.Boolean getQueuedForSending(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.QueuedForSending.toString());
	}

	/**
	 * Set value of QueuedForSending
	 * @param queuedforsending
	 */
	public final void setQueuedForSending(java.lang.Boolean queuedforsending)
	{
		setQueuedForSending(getContext(), queuedforsending);
	}

	/**
	 * Set value of QueuedForSending
	 * @param context
	 * @param queuedforsending
	 */
	public final void setQueuedForSending(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean queuedforsending)
	{
		getMendixObject().setValue(context, MemberNames.QueuedForSending.toString(), queuedforsending);
	}

	/**
	 * @return value of ResendAttempts
	 */
	public final java.lang.Integer getResendAttempts()
	{
		return getResendAttempts(getContext());
	}

	/**
	 * @param context
	 * @return value of ResendAttempts
	 */
	public final java.lang.Integer getResendAttempts(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResendAttempts.toString());
	}

	/**
	 * Set value of ResendAttempts
	 * @param resendattempts
	 */
	public final void setResendAttempts(java.lang.Integer resendattempts)
	{
		setResendAttempts(getContext(), resendattempts);
	}

	/**
	 * Set value of ResendAttempts
	 * @param context
	 * @param resendattempts
	 */
	public final void setResendAttempts(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer resendattempts)
	{
		getMendixObject().setValue(context, MemberNames.ResendAttempts.toString(), resendattempts);
	}

	/**
	 * @return value of LastSendError
	 */
	public final java.lang.String getLastSendError()
	{
		return getLastSendError(getContext());
	}

	/**
	 * @param context
	 * @return value of LastSendError
	 */
	public final java.lang.String getLastSendError(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LastSendError.toString());
	}

	/**
	 * Set value of LastSendError
	 * @param lastsenderror
	 */
	public final void setLastSendError(java.lang.String lastsenderror)
	{
		setLastSendError(getContext(), lastsenderror);
	}

	/**
	 * Set value of LastSendError
	 * @param context
	 * @param lastsenderror
	 */
	public final void setLastSendError(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String lastsenderror)
	{
		getMendixObject().setValue(context, MemberNames.LastSendError.toString(), lastsenderror);
	}

	/**
	 * @return value of LastSendAttemptAt
	 */
	public final java.util.Date getLastSendAttemptAt()
	{
		return getLastSendAttemptAt(getContext());
	}

	/**
	 * @param context
	 * @return value of LastSendAttemptAt
	 */
	public final java.util.Date getLastSendAttemptAt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.LastSendAttemptAt.toString());
	}

	/**
	 * Set value of LastSendAttemptAt
	 * @param lastsendattemptat
	 */
	public final void setLastSendAttemptAt(java.util.Date lastsendattemptat)
	{
		setLastSendAttemptAt(getContext(), lastsendattemptat);
	}

	/**
	 * Set value of LastSendAttemptAt
	 * @param context
	 * @param lastsendattemptat
	 */
	public final void setLastSendAttemptAt(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date lastsendattemptat)
	{
		getMendixObject().setValue(context, MemberNames.LastSendAttemptAt.toString(), lastsendattemptat);
	}

	/**
	 * Get value of Status
	 * @param status
	 */
	public final email_connector.proxies.ENUM_EmailStatus getStatus()
	{
		return getStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of Status
	 */
	public final email_connector.proxies.ENUM_EmailStatus getStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Status.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_EmailStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Status
	 * @param status
	 */
	public final void setStatus(email_connector.proxies.ENUM_EmailStatus status)
	{
		setStatus(getContext(), status);
	}

	/**
	 * Set value of Status
	 * @param context
	 * @param status
	 */
	public final void setStatus(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_EmailStatus status)
	{
		if (status != null) {
			getMendixObject().setValue(context, MemberNames.Status.toString(), status.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Status.toString(), null);
		}
	}

	/**
	 * @return value of isSigned
	 */
	public final java.lang.Boolean getisSigned()
	{
		return getisSigned(getContext());
	}

	/**
	 * @param context
	 * @return value of isSigned
	 */
	public final java.lang.Boolean getisSigned(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isSigned.toString());
	}

	/**
	 * Set value of isSigned
	 * @param issigned
	 */
	public final void setisSigned(java.lang.Boolean issigned)
	{
		setisSigned(getContext(), issigned);
	}

	/**
	 * Set value of isSigned
	 * @param context
	 * @param issigned
	 */
	public final void setisSigned(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean issigned)
	{
		getMendixObject().setValue(context, MemberNames.isSigned.toString(), issigned);
	}

	/**
	 * @return value of isEncrypted
	 */
	public final java.lang.Boolean getisEncrypted()
	{
		return getisEncrypted(getContext());
	}

	/**
	 * @param context
	 * @return value of isEncrypted
	 */
	public final java.lang.Boolean getisEncrypted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isEncrypted.toString());
	}

	/**
	 * Set value of isEncrypted
	 * @param isencrypted
	 */
	public final void setisEncrypted(java.lang.Boolean isencrypted)
	{
		setisEncrypted(getContext(), isencrypted);
	}

	/**
	 * Set value of isEncrypted
	 * @param context
	 * @param isencrypted
	 */
	public final void setisEncrypted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isencrypted)
	{
		getMendixObject().setValue(context, MemberNames.isEncrypted.toString(), isencrypted);
	}

	/**
	 * @return value of RecipientsToggle
	 */
	public final java.lang.Boolean getRecipientsToggle()
	{
		return getRecipientsToggle(getContext());
	}

	/**
	 * @param context
	 * @return value of RecipientsToggle
	 */
	public final java.lang.Boolean getRecipientsToggle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RecipientsToggle.toString());
	}

	/**
	 * Set value of RecipientsToggle
	 * @param recipientstoggle
	 */
	public final void setRecipientsToggle(java.lang.Boolean recipientstoggle)
	{
		setRecipientsToggle(getContext(), recipientstoggle);
	}

	/**
	 * Set value of RecipientsToggle
	 * @param context
	 * @param recipientstoggle
	 */
	public final void setRecipientsToggle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean recipientstoggle)
	{
		getMendixObject().setValue(context, MemberNames.RecipientsToggle.toString(), recipientstoggle);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailMessage_EmailTemplate
	 */
	public final email_connector.proxies.EmailTemplate getEmailMessage_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getEmailMessage_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailMessage_EmailTemplate
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailTemplate getEmailMessage_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailMessage_EmailTemplate.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailTemplate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailMessage_EmailTemplate
	 * @param emailmessage_emailtemplate
	 */
	public final void setEmailMessage_EmailTemplate(email_connector.proxies.EmailTemplate emailmessage_emailtemplate)
	{
		setEmailMessage_EmailTemplate(getContext(), emailmessage_emailtemplate);
	}

	/**
	 * Set value of EmailMessage_EmailTemplate
	 * @param context
	 * @param emailmessage_emailtemplate
	 */
	public final void setEmailMessage_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailTemplate emailmessage_emailtemplate)
	{
		if (emailmessage_emailtemplate == null) {
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailTemplate.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailTemplate.toString(), emailmessage_emailtemplate.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmailMessage_EmailAccount
	 */
	public final email_connector.proxies.EmailAccount getEmailMessage_EmailAccount() throws com.mendix.core.CoreException
	{
		return getEmailMessage_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailMessage_EmailAccount
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailAccount getEmailMessage_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmailMessage_EmailAccount.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailAccount.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmailMessage_EmailAccount
	 * @param emailmessage_emailaccount
	 */
	public final void setEmailMessage_EmailAccount(email_connector.proxies.EmailAccount emailmessage_emailaccount)
	{
		setEmailMessage_EmailAccount(getContext(), emailmessage_emailaccount);
	}

	/**
	 * Set value of EmailMessage_EmailAccount
	 * @param context
	 * @param emailmessage_emailaccount
	 */
	public final void setEmailMessage_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailAccount emailmessage_emailaccount)
	{
		if (emailmessage_emailaccount == null) {
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailAccount.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmailMessage_EmailAccount.toString(), emailmessage_emailaccount.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return emailMessageMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.EmailMessage that = (email_connector.proxies.EmailMessage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
