// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class IncomingEmailConfiguration implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject incomingEmailConfigurationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.IncomingEmailConfiguration";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		IncomingProtocol("IncomingProtocol"),
		Folder("Folder"),
		UseBatchImport("UseBatchImport"),
		BatchSize("BatchSize"),
		Handling("Handling"),
		MoveFolder("MoveFolder"),
		ProcessInlineImage("ProcessInlineImage"),
		FetchStrategy("FetchStrategy"),
		NotifyOnNewEmails("NotifyOnNewEmails"),
		ServerHost("ServerHost"),
		ServerPort("ServerPort"),
		IncomingEmailConfiguration_EmailAccount("Email_Connector.IncomingEmailConfiguration_EmailAccount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public IncomingEmailConfiguration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected IncomingEmailConfiguration(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject incomingEmailConfigurationMendixObject)
	{
		if (incomingEmailConfigurationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, incomingEmailConfigurationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.incomingEmailConfigurationMendixObject = incomingEmailConfigurationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.IncomingEmailConfiguration initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.IncomingEmailConfiguration(context, mendixObject);
	}

	public static email_connector.proxies.IncomingEmailConfiguration load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.IncomingEmailConfiguration.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.IncomingEmailConfiguration> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.IncomingEmailConfiguration.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * Get value of IncomingProtocol
	 * @param incomingprotocol
	 */
	public final email_connector.proxies.ENUM_IncomingProtocol getIncomingProtocol()
	{
		return getIncomingProtocol(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingProtocol
	 */
	public final email_connector.proxies.ENUM_IncomingProtocol getIncomingProtocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.IncomingProtocol.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_IncomingProtocol.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of IncomingProtocol
	 * @param incomingprotocol
	 */
	public final void setIncomingProtocol(email_connector.proxies.ENUM_IncomingProtocol incomingprotocol)
	{
		setIncomingProtocol(getContext(), incomingprotocol);
	}

	/**
	 * Set value of IncomingProtocol
	 * @param context
	 * @param incomingprotocol
	 */
	public final void setIncomingProtocol(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_IncomingProtocol incomingprotocol)
	{
		if (incomingprotocol != null) {
			getMendixObject().setValue(context, MemberNames.IncomingProtocol.toString(), incomingprotocol.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.IncomingProtocol.toString(), null);
		}
	}

	/**
	 * @return value of Folder
	 */
	public final java.lang.String getFolder()
	{
		return getFolder(getContext());
	}

	/**
	 * @param context
	 * @return value of Folder
	 */
	public final java.lang.String getFolder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Folder.toString());
	}

	/**
	 * Set value of Folder
	 * @param folder
	 */
	public final void setFolder(java.lang.String folder)
	{
		setFolder(getContext(), folder);
	}

	/**
	 * Set value of Folder
	 * @param context
	 * @param folder
	 */
	public final void setFolder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String folder)
	{
		getMendixObject().setValue(context, MemberNames.Folder.toString(), folder);
	}

	/**
	 * @return value of UseBatchImport
	 */
	public final java.lang.Boolean getUseBatchImport()
	{
		return getUseBatchImport(getContext());
	}

	/**
	 * @param context
	 * @return value of UseBatchImport
	 */
	public final java.lang.Boolean getUseBatchImport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UseBatchImport.toString());
	}

	/**
	 * Set value of UseBatchImport
	 * @param usebatchimport
	 */
	public final void setUseBatchImport(java.lang.Boolean usebatchimport)
	{
		setUseBatchImport(getContext(), usebatchimport);
	}

	/**
	 * Set value of UseBatchImport
	 * @param context
	 * @param usebatchimport
	 */
	public final void setUseBatchImport(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean usebatchimport)
	{
		getMendixObject().setValue(context, MemberNames.UseBatchImport.toString(), usebatchimport);
	}

	/**
	 * @return value of BatchSize
	 */
	public final java.lang.Integer getBatchSize()
	{
		return getBatchSize(getContext());
	}

	/**
	 * @param context
	 * @return value of BatchSize
	 */
	public final java.lang.Integer getBatchSize(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.BatchSize.toString());
	}

	/**
	 * Set value of BatchSize
	 * @param batchsize
	 */
	public final void setBatchSize(java.lang.Integer batchsize)
	{
		setBatchSize(getContext(), batchsize);
	}

	/**
	 * Set value of BatchSize
	 * @param context
	 * @param batchsize
	 */
	public final void setBatchSize(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer batchsize)
	{
		getMendixObject().setValue(context, MemberNames.BatchSize.toString(), batchsize);
	}

	/**
	 * Get value of Handling
	 * @param handling
	 */
	public final email_connector.proxies.ENUM_MessageHandling getHandling()
	{
		return getHandling(getContext());
	}

	/**
	 * @param context
	 * @return value of Handling
	 */
	public final email_connector.proxies.ENUM_MessageHandling getHandling(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.Handling.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_MessageHandling.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of Handling
	 * @param handling
	 */
	public final void setHandling(email_connector.proxies.ENUM_MessageHandling handling)
	{
		setHandling(getContext(), handling);
	}

	/**
	 * Set value of Handling
	 * @param context
	 * @param handling
	 */
	public final void setHandling(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_MessageHandling handling)
	{
		if (handling != null) {
			getMendixObject().setValue(context, MemberNames.Handling.toString(), handling.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.Handling.toString(), null);
		}
	}

	/**
	 * @return value of MoveFolder
	 */
	public final java.lang.String getMoveFolder()
	{
		return getMoveFolder(getContext());
	}

	/**
	 * @param context
	 * @return value of MoveFolder
	 */
	public final java.lang.String getMoveFolder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MoveFolder.toString());
	}

	/**
	 * Set value of MoveFolder
	 * @param movefolder
	 */
	public final void setMoveFolder(java.lang.String movefolder)
	{
		setMoveFolder(getContext(), movefolder);
	}

	/**
	 * Set value of MoveFolder
	 * @param context
	 * @param movefolder
	 */
	public final void setMoveFolder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String movefolder)
	{
		getMendixObject().setValue(context, MemberNames.MoveFolder.toString(), movefolder);
	}

	/**
	 * @return value of ProcessInlineImage
	 */
	public final java.lang.Boolean getProcessInlineImage()
	{
		return getProcessInlineImage(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessInlineImage
	 */
	public final java.lang.Boolean getProcessInlineImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessInlineImage.toString());
	}

	/**
	 * Set value of ProcessInlineImage
	 * @param processinlineimage
	 */
	public final void setProcessInlineImage(java.lang.Boolean processinlineimage)
	{
		setProcessInlineImage(getContext(), processinlineimage);
	}

	/**
	 * Set value of ProcessInlineImage
	 * @param context
	 * @param processinlineimage
	 */
	public final void setProcessInlineImage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processinlineimage)
	{
		getMendixObject().setValue(context, MemberNames.ProcessInlineImage.toString(), processinlineimage);
	}

	/**
	 * Get value of FetchStrategy
	 * @param fetchstrategy
	 */
	public final email_connector.proxies.ENUM_FetchStrategy getFetchStrategy()
	{
		return getFetchStrategy(getContext());
	}

	/**
	 * @param context
	 * @return value of FetchStrategy
	 */
	public final email_connector.proxies.ENUM_FetchStrategy getFetchStrategy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FetchStrategy.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_FetchStrategy.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FetchStrategy
	 * @param fetchstrategy
	 */
	public final void setFetchStrategy(email_connector.proxies.ENUM_FetchStrategy fetchstrategy)
	{
		setFetchStrategy(getContext(), fetchstrategy);
	}

	/**
	 * Set value of FetchStrategy
	 * @param context
	 * @param fetchstrategy
	 */
	public final void setFetchStrategy(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_FetchStrategy fetchstrategy)
	{
		if (fetchstrategy != null) {
			getMendixObject().setValue(context, MemberNames.FetchStrategy.toString(), fetchstrategy.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FetchStrategy.toString(), null);
		}
	}

	/**
	 * @return value of NotifyOnNewEmails
	 */
	public final java.lang.Boolean getNotifyOnNewEmails()
	{
		return getNotifyOnNewEmails(getContext());
	}

	/**
	 * @param context
	 * @return value of NotifyOnNewEmails
	 */
	public final java.lang.Boolean getNotifyOnNewEmails(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.NotifyOnNewEmails.toString());
	}

	/**
	 * Set value of NotifyOnNewEmails
	 * @param notifyonnewemails
	 */
	public final void setNotifyOnNewEmails(java.lang.Boolean notifyonnewemails)
	{
		setNotifyOnNewEmails(getContext(), notifyonnewemails);
	}

	/**
	 * Set value of NotifyOnNewEmails
	 * @param context
	 * @param notifyonnewemails
	 */
	public final void setNotifyOnNewEmails(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean notifyonnewemails)
	{
		getMendixObject().setValue(context, MemberNames.NotifyOnNewEmails.toString(), notifyonnewemails);
	}

	/**
	 * @return value of ServerHost
	 */
	public final java.lang.String getServerHost()
	{
		return getServerHost(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerHost
	 */
	public final java.lang.String getServerHost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ServerHost.toString());
	}

	/**
	 * Set value of ServerHost
	 * @param serverhost
	 */
	public final void setServerHost(java.lang.String serverhost)
	{
		setServerHost(getContext(), serverhost);
	}

	/**
	 * Set value of ServerHost
	 * @param context
	 * @param serverhost
	 */
	public final void setServerHost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serverhost)
	{
		getMendixObject().setValue(context, MemberNames.ServerHost.toString(), serverhost);
	}

	/**
	 * @return value of ServerPort
	 */
	public final java.lang.Integer getServerPort()
	{
		return getServerPort(getContext());
	}

	/**
	 * @param context
	 * @return value of ServerPort
	 */
	public final java.lang.Integer getServerPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ServerPort.toString());
	}

	/**
	 * Set value of ServerPort
	 * @param serverport
	 */
	public final void setServerPort(java.lang.Integer serverport)
	{
		setServerPort(getContext(), serverport);
	}

	/**
	 * Set value of ServerPort
	 * @param context
	 * @param serverport
	 */
	public final void setServerPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer serverport)
	{
		getMendixObject().setValue(context, MemberNames.ServerPort.toString(), serverport);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of IncomingEmailConfiguration_EmailAccount
	 */
	public final email_connector.proxies.EmailAccount getIncomingEmailConfiguration_EmailAccount() throws com.mendix.core.CoreException
	{
		return getIncomingEmailConfiguration_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of IncomingEmailConfiguration_EmailAccount
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailAccount getIncomingEmailConfiguration_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.IncomingEmailConfiguration_EmailAccount.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailAccount.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of IncomingEmailConfiguration_EmailAccount
	 * @param incomingemailconfiguration_emailaccount
	 */
	public final void setIncomingEmailConfiguration_EmailAccount(email_connector.proxies.EmailAccount incomingemailconfiguration_emailaccount)
	{
		setIncomingEmailConfiguration_EmailAccount(getContext(), incomingemailconfiguration_emailaccount);
	}

	/**
	 * Set value of IncomingEmailConfiguration_EmailAccount
	 * @param context
	 * @param incomingemailconfiguration_emailaccount
	 */
	public final void setIncomingEmailConfiguration_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailAccount incomingemailconfiguration_emailaccount)
	{
		if (incomingemailconfiguration_emailaccount == null) {
			getMendixObject().setValue(context, MemberNames.IncomingEmailConfiguration_EmailAccount.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.IncomingEmailConfiguration_EmailAccount.toString(), incomingemailconfiguration_emailaccount.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return incomingEmailConfigurationMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.IncomingEmailConfiguration that = (email_connector.proxies.IncomingEmailConfiguration) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
