// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class ModelReflectionChecker implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject modelReflectionCheckerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.ModelReflectionChecker";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ModelReflectionSynced("ModelReflectionSynced"),
		ModelReflectionChecker_EmailTemplate("Email_Connector.ModelReflectionChecker_EmailTemplate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ModelReflectionChecker(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ModelReflectionChecker(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject modelReflectionCheckerMendixObject)
	{
		if (modelReflectionCheckerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, modelReflectionCheckerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.modelReflectionCheckerMendixObject = modelReflectionCheckerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.ModelReflectionChecker initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.ModelReflectionChecker(context, mendixObject);
	}

	public static email_connector.proxies.ModelReflectionChecker load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.ModelReflectionChecker.initialize(context, mendixObject);
	}

	/**
	 * @return value of ModelReflectionSynced
	 */
	public final java.lang.Boolean getModelReflectionSynced()
	{
		return getModelReflectionSynced(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelReflectionSynced
	 */
	public final java.lang.Boolean getModelReflectionSynced(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ModelReflectionSynced.toString());
	}

	/**
	 * Set value of ModelReflectionSynced
	 * @param modelreflectionsynced
	 */
	public final void setModelReflectionSynced(java.lang.Boolean modelreflectionsynced)
	{
		setModelReflectionSynced(getContext(), modelreflectionsynced);
	}

	/**
	 * Set value of ModelReflectionSynced
	 * @param context
	 * @param modelreflectionsynced
	 */
	public final void setModelReflectionSynced(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean modelreflectionsynced)
	{
		getMendixObject().setValue(context, MemberNames.ModelReflectionSynced.toString(), modelreflectionsynced);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ModelReflectionChecker_EmailTemplate
	 */
	public final email_connector.proxies.EmailTemplate getModelReflectionChecker_EmailTemplate() throws com.mendix.core.CoreException
	{
		return getModelReflectionChecker_EmailTemplate(getContext());
	}

	/**
	 * @param context
	 * @return value of ModelReflectionChecker_EmailTemplate
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailTemplate getModelReflectionChecker_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailTemplate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ModelReflectionChecker_EmailTemplate.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailTemplate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ModelReflectionChecker_EmailTemplate
	 * @param modelreflectionchecker_emailtemplate
	 */
	public final void setModelReflectionChecker_EmailTemplate(email_connector.proxies.EmailTemplate modelreflectionchecker_emailtemplate)
	{
		setModelReflectionChecker_EmailTemplate(getContext(), modelreflectionchecker_emailtemplate);
	}

	/**
	 * Set value of ModelReflectionChecker_EmailTemplate
	 * @param context
	 * @param modelreflectionchecker_emailtemplate
	 */
	public final void setModelReflectionChecker_EmailTemplate(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailTemplate modelreflectionchecker_emailtemplate)
	{
		if (modelreflectionchecker_emailtemplate == null) {
			getMendixObject().setValue(context, MemberNames.ModelReflectionChecker_EmailTemplate.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ModelReflectionChecker_EmailTemplate.toString(), modelreflectionchecker_emailtemplate.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return modelReflectionCheckerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.ModelReflectionChecker that = (email_connector.proxies.ModelReflectionChecker) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
