// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class OAuthProvider implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject oAuthProviderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.OAuthProvider";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		ClientID("ClientID"),
		ClientSecret("ClientSecret"),
		OpenIDWellKnownMetadataUri("OpenIDWellKnownMetadataUri"),
		AuthorizationEndpoint("AuthorizationEndpoint"),
		TokenEndpoint("TokenEndpoint"),
		EmailDomain("EmailDomain"),
		CallbackOperationPath("CallbackOperationPath"),
		CallbackURL("CallbackURL"),
		OAuthType("OAuthType"),
		TenantID("TenantID");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OAuthProvider(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OAuthProvider(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject oAuthProviderMendixObject)
	{
		if (oAuthProviderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, oAuthProviderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.oAuthProviderMendixObject = oAuthProviderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.OAuthProvider initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.OAuthProvider(context, mendixObject);
	}

	public static email_connector.proxies.OAuthProvider load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.OAuthProvider.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.OAuthProvider> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.OAuthProvider.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID()
	{
		return getClientID(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientID
	 */
	public final java.lang.String getClientID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientID.toString());
	}

	/**
	 * Set value of ClientID
	 * @param clientid
	 */
	public final void setClientID(java.lang.String clientid)
	{
		setClientID(getContext(), clientid);
	}

	/**
	 * Set value of ClientID
	 * @param context
	 * @param clientid
	 */
	public final void setClientID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientid)
	{
		getMendixObject().setValue(context, MemberNames.ClientID.toString(), clientid);
	}

	/**
	 * @return value of ClientSecret
	 */
	public final java.lang.String getClientSecret()
	{
		return getClientSecret(getContext());
	}

	/**
	 * @param context
	 * @return value of ClientSecret
	 */
	public final java.lang.String getClientSecret(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ClientSecret.toString());
	}

	/**
	 * Set value of ClientSecret
	 * @param clientsecret
	 */
	public final void setClientSecret(java.lang.String clientsecret)
	{
		setClientSecret(getContext(), clientsecret);
	}

	/**
	 * Set value of ClientSecret
	 * @param context
	 * @param clientsecret
	 */
	public final void setClientSecret(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String clientsecret)
	{
		getMendixObject().setValue(context, MemberNames.ClientSecret.toString(), clientsecret);
	}

	/**
	 * @return value of OpenIDWellKnownMetadataUri
	 */
	public final java.lang.String getOpenIDWellKnownMetadataUri()
	{
		return getOpenIDWellKnownMetadataUri(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenIDWellKnownMetadataUri
	 */
	public final java.lang.String getOpenIDWellKnownMetadataUri(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OpenIDWellKnownMetadataUri.toString());
	}

	/**
	 * Set value of OpenIDWellKnownMetadataUri
	 * @param openidwellknownmetadatauri
	 */
	public final void setOpenIDWellKnownMetadataUri(java.lang.String openidwellknownmetadatauri)
	{
		setOpenIDWellKnownMetadataUri(getContext(), openidwellknownmetadatauri);
	}

	/**
	 * Set value of OpenIDWellKnownMetadataUri
	 * @param context
	 * @param openidwellknownmetadatauri
	 */
	public final void setOpenIDWellKnownMetadataUri(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String openidwellknownmetadatauri)
	{
		getMendixObject().setValue(context, MemberNames.OpenIDWellKnownMetadataUri.toString(), openidwellknownmetadatauri);
	}

	/**
	 * @return value of AuthorizationEndpoint
	 */
	public final java.lang.String getAuthorizationEndpoint()
	{
		return getAuthorizationEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of AuthorizationEndpoint
	 */
	public final java.lang.String getAuthorizationEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AuthorizationEndpoint.toString());
	}

	/**
	 * Set value of AuthorizationEndpoint
	 * @param authorizationendpoint
	 */
	public final void setAuthorizationEndpoint(java.lang.String authorizationendpoint)
	{
		setAuthorizationEndpoint(getContext(), authorizationendpoint);
	}

	/**
	 * Set value of AuthorizationEndpoint
	 * @param context
	 * @param authorizationendpoint
	 */
	public final void setAuthorizationEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String authorizationendpoint)
	{
		getMendixObject().setValue(context, MemberNames.AuthorizationEndpoint.toString(), authorizationendpoint);
	}

	/**
	 * @return value of TokenEndpoint
	 */
	public final java.lang.String getTokenEndpoint()
	{
		return getTokenEndpoint(getContext());
	}

	/**
	 * @param context
	 * @return value of TokenEndpoint
	 */
	public final java.lang.String getTokenEndpoint(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TokenEndpoint.toString());
	}

	/**
	 * Set value of TokenEndpoint
	 * @param tokenendpoint
	 */
	public final void setTokenEndpoint(java.lang.String tokenendpoint)
	{
		setTokenEndpoint(getContext(), tokenendpoint);
	}

	/**
	 * Set value of TokenEndpoint
	 * @param context
	 * @param tokenendpoint
	 */
	public final void setTokenEndpoint(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tokenendpoint)
	{
		getMendixObject().setValue(context, MemberNames.TokenEndpoint.toString(), tokenendpoint);
	}

	/**
	 * @return value of EmailDomain
	 */
	public final java.lang.String getEmailDomain()
	{
		return getEmailDomain(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailDomain
	 */
	public final java.lang.String getEmailDomain(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmailDomain.toString());
	}

	/**
	 * Set value of EmailDomain
	 * @param emaildomain
	 */
	public final void setEmailDomain(java.lang.String emaildomain)
	{
		setEmailDomain(getContext(), emaildomain);
	}

	/**
	 * Set value of EmailDomain
	 * @param context
	 * @param emaildomain
	 */
	public final void setEmailDomain(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String emaildomain)
	{
		getMendixObject().setValue(context, MemberNames.EmailDomain.toString(), emaildomain);
	}

	/**
	 * @return value of CallbackOperationPath
	 */
	public final java.lang.String getCallbackOperationPath()
	{
		return getCallbackOperationPath(getContext());
	}

	/**
	 * @param context
	 * @return value of CallbackOperationPath
	 */
	public final java.lang.String getCallbackOperationPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CallbackOperationPath.toString());
	}

	/**
	 * Set value of CallbackOperationPath
	 * @param callbackoperationpath
	 */
	public final void setCallbackOperationPath(java.lang.String callbackoperationpath)
	{
		setCallbackOperationPath(getContext(), callbackoperationpath);
	}

	/**
	 * Set value of CallbackOperationPath
	 * @param context
	 * @param callbackoperationpath
	 */
	public final void setCallbackOperationPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String callbackoperationpath)
	{
		getMendixObject().setValue(context, MemberNames.CallbackOperationPath.toString(), callbackoperationpath);
	}

	/**
	 * @return value of CallbackURL
	 */
	public final java.lang.String getCallbackURL()
	{
		return getCallbackURL(getContext());
	}

	/**
	 * @param context
	 * @return value of CallbackURL
	 */
	public final java.lang.String getCallbackURL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CallbackURL.toString());
	}

	/**
	 * Set value of CallbackURL
	 * @param callbackurl
	 */
	public final void setCallbackURL(java.lang.String callbackurl)
	{
		setCallbackURL(getContext(), callbackurl);
	}

	/**
	 * Set value of CallbackURL
	 * @param context
	 * @param callbackurl
	 */
	public final void setCallbackURL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String callbackurl)
	{
		getMendixObject().setValue(context, MemberNames.CallbackURL.toString(), callbackurl);
	}

	/**
	 * Get value of OAuthType
	 * @param oauthtype
	 */
	public final email_connector.proxies.ENUM_OAuthType getOAuthType()
	{
		return getOAuthType(getContext());
	}

	/**
	 * @param context
	 * @return value of OAuthType
	 */
	public final email_connector.proxies.ENUM_OAuthType getOAuthType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OAuthType.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_OAuthType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OAuthType
	 * @param oauthtype
	 */
	public final void setOAuthType(email_connector.proxies.ENUM_OAuthType oauthtype)
	{
		setOAuthType(getContext(), oauthtype);
	}

	/**
	 * Set value of OAuthType
	 * @param context
	 * @param oauthtype
	 */
	public final void setOAuthType(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_OAuthType oauthtype)
	{
		if (oauthtype != null) {
			getMendixObject().setValue(context, MemberNames.OAuthType.toString(), oauthtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.OAuthType.toString(), null);
		}
	}

	/**
	 * @return value of TenantID
	 */
	public final java.lang.String getTenantID()
	{
		return getTenantID(getContext());
	}

	/**
	 * @param context
	 * @return value of TenantID
	 */
	public final java.lang.String getTenantID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TenantID.toString());
	}

	/**
	 * Set value of TenantID
	 * @param tenantid
	 */
	public final void setTenantID(java.lang.String tenantid)
	{
		setTenantID(getContext(), tenantid);
	}

	/**
	 * Set value of TenantID
	 * @param context
	 * @param tenantid
	 */
	public final void setTenantID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tenantid)
	{
		getMendixObject().setValue(context, MemberNames.TenantID.toString(), tenantid);
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return oAuthProviderMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.OAuthProvider that = (email_connector.proxies.OAuthProvider) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
