// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class OutgoingServer implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject outgoingServerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.OutgoingServer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HostName("HostName"),
		Port("Port"),
		OutgoingProtocol("OutgoingProtocol"),
		SSL("SSL"),
		TLS("TLS"),
		SendSMTP("SendSMTP"),
		SelectedOutgoingServer("SelectedOutgoingServer"),
		OutgoingServer_EmailProvider("Email_Connector.OutgoingServer_EmailProvider");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public OutgoingServer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected OutgoingServer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject outgoingServerMendixObject)
	{
		if (outgoingServerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, outgoingServerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.outgoingServerMendixObject = outgoingServerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.OutgoingServer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.OutgoingServer(context, mendixObject);
	}

	public static email_connector.proxies.OutgoingServer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.OutgoingServer.initialize(context, mendixObject);
	}

	/**
	 * @return value of HostName
	 */
	public final java.lang.String getHostName()
	{
		return getHostName(getContext());
	}

	/**
	 * @param context
	 * @return value of HostName
	 */
	public final java.lang.String getHostName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.HostName.toString());
	}

	/**
	 * Set value of HostName
	 * @param hostname
	 */
	public final void setHostName(java.lang.String hostname)
	{
		setHostName(getContext(), hostname);
	}

	/**
	 * Set value of HostName
	 * @param context
	 * @param hostname
	 */
	public final void setHostName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String hostname)
	{
		getMendixObject().setValue(context, MemberNames.HostName.toString(), hostname);
	}

	/**
	 * @return value of Port
	 */
	public final java.lang.Integer getPort()
	{
		return getPort(getContext());
	}

	/**
	 * @param context
	 * @return value of Port
	 */
	public final java.lang.Integer getPort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Port.toString());
	}

	/**
	 * Set value of Port
	 * @param port
	 */
	public final void setPort(java.lang.Integer port)
	{
		setPort(getContext(), port);
	}

	/**
	 * Set value of Port
	 * @param context
	 * @param port
	 */
	public final void setPort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer port)
	{
		getMendixObject().setValue(context, MemberNames.Port.toString(), port);
	}

	/**
	 * Get value of OutgoingProtocol
	 * @param outgoingprotocol
	 */
	public final email_connector.proxies.ENUM_OutgoingProtocol getOutgoingProtocol()
	{
		return getOutgoingProtocol(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingProtocol
	 */
	public final email_connector.proxies.ENUM_OutgoingProtocol getOutgoingProtocol(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.OutgoingProtocol.toString());
		if (obj == null) {
			return null;
		}
		return email_connector.proxies.ENUM_OutgoingProtocol.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of OutgoingProtocol
	 * @param outgoingprotocol
	 */
	public final void setOutgoingProtocol(email_connector.proxies.ENUM_OutgoingProtocol outgoingprotocol)
	{
		setOutgoingProtocol(getContext(), outgoingprotocol);
	}

	/**
	 * Set value of OutgoingProtocol
	 * @param context
	 * @param outgoingprotocol
	 */
	public final void setOutgoingProtocol(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.ENUM_OutgoingProtocol outgoingprotocol)
	{
		if (outgoingprotocol != null) {
			getMendixObject().setValue(context, MemberNames.OutgoingProtocol.toString(), outgoingprotocol.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.OutgoingProtocol.toString(), null);
		}
	}

	/**
	 * @return value of SSL
	 */
	public final java.lang.Boolean getSSL()
	{
		return getSSL(getContext());
	}

	/**
	 * @param context
	 * @return value of SSL
	 */
	public final java.lang.Boolean getSSL(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SSL.toString());
	}

	/**
	 * Set value of SSL
	 * @param ssl
	 */
	public final void setSSL(java.lang.Boolean ssl)
	{
		setSSL(getContext(), ssl);
	}

	/**
	 * Set value of SSL
	 * @param context
	 * @param ssl
	 */
	public final void setSSL(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean ssl)
	{
		getMendixObject().setValue(context, MemberNames.SSL.toString(), ssl);
	}

	/**
	 * @return value of TLS
	 */
	public final java.lang.Boolean getTLS()
	{
		return getTLS(getContext());
	}

	/**
	 * @param context
	 * @return value of TLS
	 */
	public final java.lang.Boolean getTLS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TLS.toString());
	}

	/**
	 * Set value of TLS
	 * @param tls
	 */
	public final void setTLS(java.lang.Boolean tls)
	{
		setTLS(getContext(), tls);
	}

	/**
	 * Set value of TLS
	 * @param context
	 * @param tls
	 */
	public final void setTLS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean tls)
	{
		getMendixObject().setValue(context, MemberNames.TLS.toString(), tls);
	}

	/**
	 * @return value of SendSMTP
	 */
	public final java.lang.Boolean getSendSMTP()
	{
		return getSendSMTP(getContext());
	}

	/**
	 * @param context
	 * @return value of SendSMTP
	 */
	public final java.lang.Boolean getSendSMTP(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SendSMTP.toString());
	}

	/**
	 * Set value of SendSMTP
	 * @param sendsmtp
	 */
	public final void setSendSMTP(java.lang.Boolean sendsmtp)
	{
		setSendSMTP(getContext(), sendsmtp);
	}

	/**
	 * Set value of SendSMTP
	 * @param context
	 * @param sendsmtp
	 */
	public final void setSendSMTP(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sendsmtp)
	{
		getMendixObject().setValue(context, MemberNames.SendSMTP.toString(), sendsmtp);
	}

	/**
	 * @return value of SelectedOutgoingServer
	 */
	public final java.lang.Boolean getSelectedOutgoingServer()
	{
		return getSelectedOutgoingServer(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedOutgoingServer
	 */
	public final java.lang.Boolean getSelectedOutgoingServer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SelectedOutgoingServer.toString());
	}

	/**
	 * Set value of SelectedOutgoingServer
	 * @param selectedoutgoingserver
	 */
	public final void setSelectedOutgoingServer(java.lang.Boolean selectedoutgoingserver)
	{
		setSelectedOutgoingServer(getContext(), selectedoutgoingserver);
	}

	/**
	 * Set value of SelectedOutgoingServer
	 * @param context
	 * @param selectedoutgoingserver
	 */
	public final void setSelectedOutgoingServer(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean selectedoutgoingserver)
	{
		getMendixObject().setValue(context, MemberNames.SelectedOutgoingServer.toString(), selectedoutgoingserver);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of OutgoingServer_EmailProvider
	 */
	public final email_connector.proxies.EmailProvider getOutgoingServer_EmailProvider() throws com.mendix.core.CoreException
	{
		return getOutgoingServer_EmailProvider(getContext());
	}

	/**
	 * @param context
	 * @return value of OutgoingServer_EmailProvider
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailProvider getOutgoingServer_EmailProvider(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailProvider result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.OutgoingServer_EmailProvider.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailProvider.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of OutgoingServer_EmailProvider
	 * @param outgoingserver_emailprovider
	 */
	public final void setOutgoingServer_EmailProvider(email_connector.proxies.EmailProvider outgoingserver_emailprovider)
	{
		setOutgoingServer_EmailProvider(getContext(), outgoingserver_emailprovider);
	}

	/**
	 * Set value of OutgoingServer_EmailProvider
	 * @param context
	 * @param outgoingserver_emailprovider
	 */
	public final void setOutgoingServer_EmailProvider(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailProvider outgoingserver_emailprovider)
	{
		if (outgoingserver_emailprovider == null) {
			getMendixObject().setValue(context, MemberNames.OutgoingServer_EmailProvider.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.OutgoingServer_EmailProvider.toString(), outgoingserver_emailprovider.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return outgoingServerMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.OutgoingServer that = (email_connector.proxies.OutgoingServer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
