// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class Pk12Certificate extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.Pk12Certificate";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Passphrase("Passphrase"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Pk12Certificate_EmailAccount("Email_Connector.Pk12Certificate_EmailAccount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Pk12Certificate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Pk12Certificate(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pk12CertificateMendixObject)
	{
		super(context, pk12CertificateMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, pk12CertificateMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.Pk12Certificate initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.Pk12Certificate(context, mendixObject);
	}

	public static email_connector.proxies.Pk12Certificate load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.Pk12Certificate.initialize(context, mendixObject);
	}

	public static java.util.List<email_connector.proxies.Pk12Certificate> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> email_connector.proxies.Pk12Certificate.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Passphrase
	 */
	public final java.lang.String getPassphrase()
	{
		return getPassphrase(getContext());
	}

	/**
	 * @param context
	 * @return value of Passphrase
	 */
	public final java.lang.String getPassphrase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Passphrase.toString());
	}

	/**
	 * Set value of Passphrase
	 * @param passphrase
	 */
	public final void setPassphrase(java.lang.String passphrase)
	{
		setPassphrase(getContext(), passphrase);
	}

	/**
	 * Set value of Passphrase
	 * @param context
	 * @param passphrase
	 */
	public final void setPassphrase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String passphrase)
	{
		getMendixObject().setValue(context, MemberNames.Passphrase.toString(), passphrase);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Pk12Certificate_EmailAccount
	 */
	public final email_connector.proxies.EmailAccount getPk12Certificate_EmailAccount() throws com.mendix.core.CoreException
	{
		return getPk12Certificate_EmailAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of Pk12Certificate_EmailAccount
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.EmailAccount getPk12Certificate_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.EmailAccount result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Pk12Certificate_EmailAccount.toString());
		if (identifier != null) {
			result = email_connector.proxies.EmailAccount.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Pk12Certificate_EmailAccount
	 * @param pk12certificate_emailaccount
	 */
	public final void setPk12Certificate_EmailAccount(email_connector.proxies.EmailAccount pk12certificate_emailaccount)
	{
		setPk12Certificate_EmailAccount(getContext(), pk12certificate_emailaccount);
	}

	/**
	 * Set value of Pk12Certificate_EmailAccount
	 * @param context
	 * @param pk12certificate_emailaccount
	 */
	public final void setPk12Certificate_EmailAccount(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.EmailAccount pk12certificate_emailaccount)
	{
		if (pk12certificate_emailaccount == null) {
			getMendixObject().setValue(context, MemberNames.Pk12Certificate_EmailAccount.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Pk12Certificate_EmailAccount.toString(), pk12certificate_emailaccount.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.Pk12Certificate that = (email_connector.proxies.Pk12Certificate) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
