// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package email_connector.proxies;

public class Pk12Certificate_NPE implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject pk12Certificate_NPEMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Email_Connector.Pk12Certificate_NPE";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Passphrase("Passphrase"),
		Pk12Certificate_NPE_Pk12Certificate("Email_Connector.Pk12Certificate_NPE_Pk12Certificate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Pk12Certificate_NPE(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Pk12Certificate_NPE(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject pk12Certificate_NPEMendixObject)
	{
		if (pk12Certificate_NPEMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, pk12Certificate_NPEMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.pk12Certificate_NPEMendixObject = pk12Certificate_NPEMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static email_connector.proxies.Pk12Certificate_NPE initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new email_connector.proxies.Pk12Certificate_NPE(context, mendixObject);
	}

	public static email_connector.proxies.Pk12Certificate_NPE load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return email_connector.proxies.Pk12Certificate_NPE.initialize(context, mendixObject);
	}

	/**
	 * @return value of Passphrase
	 */
	public final java.lang.String getPassphrase()
	{
		return getPassphrase(getContext());
	}

	/**
	 * @param context
	 * @return value of Passphrase
	 */
	public final java.lang.String getPassphrase(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Passphrase.toString());
	}

	/**
	 * Set value of Passphrase
	 * @param passphrase
	 */
	public final void setPassphrase(java.lang.String passphrase)
	{
		setPassphrase(getContext(), passphrase);
	}

	/**
	 * Set value of Passphrase
	 * @param context
	 * @param passphrase
	 */
	public final void setPassphrase(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String passphrase)
	{
		getMendixObject().setValue(context, MemberNames.Passphrase.toString(), passphrase);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Pk12Certificate_NPE_Pk12Certificate
	 */
	public final email_connector.proxies.Pk12Certificate getPk12Certificate_NPE_Pk12Certificate() throws com.mendix.core.CoreException
	{
		return getPk12Certificate_NPE_Pk12Certificate(getContext());
	}

	/**
	 * @param context
	 * @return value of Pk12Certificate_NPE_Pk12Certificate
	 * @throws com.mendix.core.CoreException
	 */
	public final email_connector.proxies.Pk12Certificate getPk12Certificate_NPE_Pk12Certificate(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		email_connector.proxies.Pk12Certificate result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Pk12Certificate_NPE_Pk12Certificate.toString());
		if (identifier != null) {
			result = email_connector.proxies.Pk12Certificate.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Pk12Certificate_NPE_Pk12Certificate
	 * @param pk12certificate_npe_pk12certificate
	 */
	public final void setPk12Certificate_NPE_Pk12Certificate(email_connector.proxies.Pk12Certificate pk12certificate_npe_pk12certificate)
	{
		setPk12Certificate_NPE_Pk12Certificate(getContext(), pk12certificate_npe_pk12certificate);
	}

	/**
	 * Set value of Pk12Certificate_NPE_Pk12Certificate
	 * @param context
	 * @param pk12certificate_npe_pk12certificate
	 */
	public final void setPk12Certificate_NPE_Pk12Certificate(com.mendix.systemwideinterfaces.core.IContext context, email_connector.proxies.Pk12Certificate pk12certificate_npe_pk12certificate)
	{
		if (pk12certificate_npe_pk12certificate == null) {
			getMendixObject().setValue(context, MemberNames.Pk12Certificate_NPE_Pk12Certificate.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Pk12Certificate_NPE_Pk12Certificate.toString(), pk12certificate_npe_pk12certificate.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return pk12Certificate_NPEMendixObject;
	}

	@java.lang.Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final email_connector.proxies.Pk12Certificate_NPE that = (email_connector.proxies.Pk12Certificate_NPE) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
